=== linked-art/linked.art/docs/api/1.0/schema/concept.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://linked.art/api/1.0/schema/concept.json",
	"title": "Concept Schema",
	"description": "_crm:E55\\_Type_\nConcepts, Subjects and other categorizations.\nSee: [API](https://linked.art/api/1.0/endpoint/place/) | [Model](https://linked.art/model/)",
	"type": "object",
	"properties": {
		"@context": {"$ref": "core.json#/definitions/ContextStringOrArray"},
		"id": {"$ref": "core.json#/definitions/idProp"},				
		"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
			{"title": "Specific", "type": "string", "enum": ["Type", "Currency", "Material", "Language", "MeasurementUnit"]}]},
		"_label": {"$ref": "core.json#/definitions/labelProp"},
		"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
		"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
		"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},
		"equivalent": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/equivalentProp"}, 
			{"title": "Specific", "description": "List of concept entities", "type": "array", "items": {"$ref": "core.json#/definitions/AnyTypeRef"}}]},
		"representation": {"$ref": "core.json#/definitions/representationProp"},
		"member_of": {"$ref": "core.json#/definitions/member_ofSetProp"},
		"subject_of": {"$ref": "core.json#/definitions/subject_ofProp"},
		"attributed_by": {"$ref": "core.json#/definitions/attributed_byRelProp"},
		"created_by": {"title": "crm:P94i_was_created_by", "$ref": "core.json#/definitions/Creation"},

		"broader": {
			"title": "skos:broader",
			"description": "This concept is contained within one or more larger/broader concept entities",
			"type": "array", 
			"items": {"$ref": "core.json#/definitions/AnyTypeRef"}
		}
	},
	"required": ["@context", "id", "type", "_label"],
	"additionalProperties": false
}

=== linked-art/linked.art/docs/example/concept/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/concept/1",
  "type": "Type",
  "_label": "History of France",
  "identified_by": [
    {
      "type": "Name",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300404670",
          "type": "Type",
          "_label": "Primary Name"
        }
      ],
      "content": "History of France"
    }
  ],
  "member_of": [
    {
      "type": "Set",
      "_label": "Useful History Concepts"
    }
  ],
  "broader": [
    {
      "type": "Type",
      "_label": "History of Europe"
    }
  ],
  "equivalent": [
    {
      "id": "http://id.loc.gov/authorities/subjects/sh85051256",
      "type": "Type"
    }
  ],
  "created_by": {
    "type": "Creation",
    "_label": "Concept Creation",
    "influenced_by": [
      {
        "type": "Type",
        "_label": "History"
      },
      {
        "type": "Place",
        "_label": "France"
      }
    ]
  }
}

=== linked-art/linked.art/docs/example/concept/painting/2.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/concept/painting/2",
  "type": "Type",
  "_label": "Local Copy of Painting",
  "identified_by": [
    {
      "type": "Name",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300404670",
          "type": "Type",
          "_label": "Primary Name"
        }
      ],
      "content": "Painting"
    }
  ],
  "equivalent": [
    {
      "id": "http://vocab.getty.edu/aat/300033618",
      "type": "Type",
      "_label": "painting (visual works)"
    }
  ]
}

=== linked-art/linked.art/docs/example/concept/painting/4.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/concept/painting/4",
  "type": "Type",
  "_label": "Local Copy of Painting",
  "member_of": [
    {
      "id": "https://linked.art/example/set/conceptScheme",
      "type": "Set",
      "_label": "Local Concept Scheme"
    }
  ]
}

=== linked-art/linked.art/docs/example/concept/historyFrance/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/concept/historyFrance/1",
  "type": "Type",
  "_label": "History of France",
  "created_by": {
    "type": "Creation",
    "influenced_by": [
      {
        "id": "https://linked.art/example/concept/history",
        "type": "Type",
        "_label": "History"
      },
      {
        "id": "https://linked.art/example/place/france",
        "type": "Place",
        "_label": "France"
      }
    ]
  }
}

=== linked-art/linked.art/docs/example/concept/painting/3.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/concept/painting/3",
  "type": "Type",
  "_label": "Local Copy of Painting",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300435443",
      "type": "Type",
      "_label": "type of work"
    }
  ],
  "equivalent": [
    {
      "id": "http://vocab.getty.edu/aat/300033618",
      "type": "Type",
      "_label": "painting (visual works)"
    }
  ],
  "broader": [
    {
      "id": "http://vocab.getty.edu/aat/300191086",
      "type": "Type",
      "_label": "visual works"
    }
  ]
}
