=== linked-art/linked.art/docs/api/1.0/schema/group.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://linked.art/api/1.0/schema/group.json",
	"title": "Group Schema",
	"description": "_crm:E74\\_Group_\nA Group of People and/or other Groups.\nSee: [API](https://linked.art/api/1.0/endpoint/group/) | [Model](https://linked.art/model/actor/)",	
	"type": "object",
	"properties": {
		"@context": {"$ref": "core.json#/$defs/ContextStringOrArray"},
		"id": {"$ref": "core.json#/$defs/idProp"},
		"type": {"allOf": [{"title": "General", "$ref": "core.json#/$defs/typeProp"},
			{"title": "Specific", "type": "string", "const": "Group"}]},
		"_label": {"$ref": "core.json#/$defs/labelProp"},
		"identified_by": {"$ref": "core.json#/$defs/identified_byProp"},
		"classified_as": {"$ref": "core.json#/$defs/classified_asProp"},
		"referred_to_by": {"$ref": "core.json#/$defs/referred_to_byProp"},
		"equivalent": {"allOf": [{"title": "General", "$ref": "core.json#/$defs/equivalentProp"},
			{"title": "Specific", "description": "List of `Group` entities", "type": "array", "items": {"$ref": "core.json#/$defs/GroupRef"}}]},
		"representation": {"$ref": "core.json#/$defs/representationProp"},
		"member_of": {"$ref": "core.json#/$defs/member_ofGroupProp"},
		"subject_of": {"$ref": "core.json#/$defs/subject_ofProp"},
		"attributed_by": {"$ref": "core.json#/$defs/attributed_byRelProp"},

		"carried_out": {"$ref": "core.json#/$defs/carried_outProp"},
		"participated_in": {"$ref": "core.json#/$defs/participated_inProp"},
		"contact_point": {"$ref": "core.json#/$defs/contact_pointProp"},
		"residence": {"$ref": "core.json#/$defs/residenceProp"},

		"formed_by": {
			"title": "crm:P95i_was_formed_by",
			"description": "The activity of forming or creating the Group",
			"$ref": "#/$defs/Formation"
		},
		"dissolved_by": {
			"title": "crm:P99i_was_dissolved_by",
			"description": "The activity of dissolving or ending the Group",
			"$ref": "#/$defs/Dissolution"
		}

	},
	"$defs": {
		"Formation": {
			"title": "crm:E66_Formation",
			"description": "The activity which formed or created the Group",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/$defs/typeProp"},
					{"title": "Specific", "type": "string", "const": "Formation"}]},
				"_label": {"$ref": "core.json#/$defs/labelProp"},
				"identified_by": {"$ref": "core.json#/$defs/identified_byProp"},
				"classified_as": {"$ref": "core.json#/$defs/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/$defs/referred_to_byProp"},

				"took_place_at": {"$ref": "core.json#/$defs/took_place_atProp"},
				"timespan": {"$ref": "core.json#/$defs/timespanProp"},
				"caused_by": {"$ref": "core.json#/$defs/caused_byProp"},
				"carried_out_by": {"$ref": "core.json#/$defs/carried_out_byProp"},
				"used_specific_object": {"$ref": "core.json#/$defs/used_specific_objectProp"},
				"influenced_by": {"$ref": "core.json#/$defs/influenced_byProp"},
				"technique": {"$ref": "core.json#/$defs/techniqueProp"},
				"during": {"$ref": "core.json#/$defs/duringProp"},
				"after": {"$ref": "core.json#/$defs/afterProp"},
				"before": {"$ref": "core.json#/$defs/beforeProp"},

				"part_of": {"title": "crm:P9i_forms_part_of", "description": "An identified event or activity which this formation is part of", "$ref": "core.json#/$defs/EventRefOrActivityRef"}
			}
		},
		"Dissolution": {
			"title": "crm:E68_Dissolution",
			"description": "The event which dissolved or ended the Group",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/$defs/typeProp"},
					{"title": "Specific", "type": "string", "const": "Dissolution"}]},
				"_label": {"$ref": "core.json#/$defs/labelProp"},
				"identified_by": {"$ref": "core.json#/$defs/identified_byProp"},
				"classified_as": {"$ref": "core.json#/$defs/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/$defs/referred_to_byProp"},
				"took_place_at": {"$ref": "core.json#/$defs/took_place_atProp"},
				"timespan": {"$ref": "core.json#/$defs/timespanProp"},
				"caused_by": {"$ref": "core.json#/$defs/caused_byProp"},
				"influenced_by": {"$ref": "core.json#/$defs/influenced_byProp"},
				"during": {"$ref": "core.json#/$defs/duringProp"},
				"after": {"$ref": "core.json#/$defs/afterProp"},
				"before": {"$ref": "core.json#/$defs/beforeProp"},
				"part_of": {"title": "crm:P9i_forms_part_of", "description": "An identified event or activity which this dissolution is part of", "$ref": "core.json#/$defs/EventRefOrActivityRef"}
			}
		}
	},
	"required": ["@context", "id", "type", "_label"],
	"additionalProperties": false
}

=== linked-art/linked.art/docs/example/group/rembrandthuis/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/group/rembrandthuis/1",
  "type": "Group",
  "_label": "Rembrandt House Museum",
  "contact_point": [
    {
      "type": "Identifier",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300386983",
          "type": "Type",
          "_label": "Street Address"
        }
      ],
      "content": "Jodenbreestraat 4, 1011 NK Amsterdam"
    },
    {
      "type": "Identifier",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435688",
          "type": "Type",
          "_label": "Telephone Number"
        }
      ],
      "content": "+31-20-520-0400"
    },
    {
      "type": "Identifier",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435686",
          "type": "Type",
          "_label": "Email Address"
        }
      ],
      "content": "museum@rembrandthuis.nl"
    }
  ]
}

=== linked-art/linked.art/docs/example/group/harwoodstudio/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/group/harwoodstudio/1",
  "type": "Group",
  "_label": "Studio of Francis Harwood",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300404275",
      "type": "Type",
      "_label": "Studio"
    }
  ],
  "formed_by": {
    "type": "Formation",
    "influenced_by": [
      {
        "id": "http://vocab.getty.edu/ulan/500015886",
        "type": "Person",
        "_label": "Francis Harwood"
      }
    ]
  }
}

=== linked-art/linked.art/docs/example/group/0.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/group/0",
  "type": "Group",
  "_label": "Camden Town Group",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300026009",
      "type": "Type",
      "_label": "Society"
    },
    {
      "id": "http://vocab.getty.edu/aat/300111159",
      "type": "Type",
      "_label": "British",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300379842",
          "type": "Type",
          "_label": "Nationality"
        }
      ]
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "content": "Camden Town Group",
      "language": [
        {
          "id": "http://vocab.getty.edu/aat/300388277",
          "type": "Language",
          "_label": "English"
        }
      ]
    }
  ],
  "referred_to_by": [
    {
      "type": "LinguisticObject",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435422",
          "type": "Type",
          "_label": "Biography Statement",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300418049",
              "type": "Type",
              "_label": "Brief Text"
            }
          ]
        }
      ],
      "content": "A group of British painters formed in 1911; although it only lasted two years, its name is used in a broader sense to characterize a particular strain of British painting from about 1905 to 1920."
    }
  ],
  "carried_out": [
    {
      "type": "Activity",
      "_label": "Active Dates",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300393177",
          "type": "Type",
          "_label": "Professional Activities"
        }
      ],
      "timespan": {
        "type": "TimeSpan",
        "begin_of_the_begin": "1911-01-01T00:00:00Z",
        "end_of_the_end": "1913-12-31T23:59:59Z"
      }
    }
  ],
  "formed_by": {
    "type": "Formation",
    "_label": "Formation of the Group",
    "timespan": {
      "type": "TimeSpan",
      "_label": "1911",
      "begin_of_the_begin": "1911-01-01T00:00:00Z",
      "end_of_the_end": "1911-12-31T23:59:59Z"
    },
    "took_place_at": [
      {
        "type": "Place",
        "_label": "London"
      }
    ]
  },
  "dissolved_by": {
    "type": "Dissolution",
    "_label": "Dissolution of the Group",
    "timespan": {
      "type": "TimeSpan",
      "_label": "1913",
      "begin_of_the_begin": "1913-01-01T00:00:00Z",
      "end_of_the_end": "1913-12-31T23:59:59Z"
    },
    "took_place_at": [
      {
        "type": "Place",
        "_label": "London"
      }
    ]
  },
  "residence": [
    {
      "type": "Place",
      "_label": "London"
    }
  ],
  "equivalent": [
    {
      "id": "http://vocab.getty.edu/ulan/500117318",
      "type": "Group",
      "_label": "Camden Town Group"
    }
  ],
  "attributed_by": [
    {
      "type": "AttributeAssignment",
      "_label": "Related Group",
      "assigned": [
        {
          "id": "http://vocab.getty.edu/ulan/500117319",
          "type": "Group",
          "_label": "London Group"
        }
      ]
    }
  ]
}

=== linked-art/linked.art/docs/example/group/rembrandthuis/2.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/group/rembrandthuis/2",
  "type": "Group",
  "_label": "Rembrandt House Museum",
  "formed_by": {
    "type": "Formation",
    "timespan": {
      "type": "TimeSpan",
      "begin_of_the_begin": "1911-06-10T00:00:00Z",
      "end_of_the_end": "1911-06-10T23:59:59Z"
    }
  }
}
