=== linked-art/linked.art/docs/api/1.0/schema/image.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://linked.art/api/1.0/schema/image.json",
	"title": "Visual Content Schema",
	"description": "_crm:E36\\_Visual\\_Item_\nThe visual content of a work.\nSee: [API](https://linked.art/api/1.0/endpoint/visual_work/) | [Model](https://linked.art/model/object/aboutness/#physical-object-and-visual-work)",
	"type": "object",
	"properties": {
		"@context": {"$ref": "core.json#/definitions/ContextStringOrArray"},
		"id": {"$ref": "core.json#/definitions/idProp"},				
		"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
			{"title": "Specific", "type": "string", "const": "VisualItem"}]},
		"_label": {"$ref": "core.json#/definitions/labelProp"},
		"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
		"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
		"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},
		"equivalent": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/equivalentProp"}, 
			{"title": "Specific", "description": "List of equivalent `VisualItem` entities", "type": "array", "items": {"$ref": "core.json#/definitions/VisualItemRef"}}]},
		"member_of": {"$ref": "core.json#/definitions/member_ofSetProp"},
		"subject_of": {"$ref": "core.json#/definitions/subject_ofProp"},
		"attributed_by": {"$ref": "core.json#/definitions/attributed_byRelProp"},
		"dimension": {"$ref": "core.json#/definitions/dimensionProp"},
		"subject_to": {"$ref": "core.json#/definitions/subject_toProp"},
		"part_of": {
			"title": "crm:P106i_forms_part_of",
			"description": "Reference to another Visual Item of which this is part", 
			"type": "array",
			"items": {"$ref": "core.json#/definitions/VisualItemRef"}},

		"about": {"$ref": "core.json#/definitions/aboutProp"},
		"created_by": {"title": "crm:P94i_was_created_by", "$ref": "core.json#/definitions/Creation"},
		"represents": {"title": "crm:P138_represents", "description": "An entity which is represented in this image content", "type": "array", "items": {"$ref": "core.json#/definitions/AnyRef"}},
		"represents_instance_of_type": {"title": "la:represents_instance_of_type", "description": "A Type of an entity, which is represented in this image content", "type": "array", "items": {"$ref": "core.json#/definitions/Concept"}},
		"used_for": {"title": "crm:P16i_was_used_for", "description": "", "type": "array", "items": {"$ref": "core.json#/definitions/Activity"}}

	},
	"required": ["@context", "id", "type", "_label"],
	"additionalProperties": false
}

=== linked-art/linked.art/docs/example/visual/spring/5.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/visual/spring/5",
  "type": "VisualItem",
  "_label": "Visual Content of Spring",
  "represents_instance_of_type": [
    {
      "id": "http://vocab.getty.edu/aat/300046218",
      "type": "Type",
      "_label": "Parasol"
    }
  ]
}

=== linked-art/linked.art/docs/example/visual/spring/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/visual/spring/1",
  "type": "VisualItem",
  "_label": "Visual Content of Spring",
  "represents": [
    {
      "id": "https://linked.art/example/person/jeanne",
      "type": "Person",
      "_label": "Jeanne Demarsy"
    }
  ]
}

=== linked-art/linked.art/docs/example/visual/harpers/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/visual/harpers/1",
  "type": "VisualItem",
  "_label": "Visual Content of Harpers",
  "referred_to_by": [
    {
      "type": "LinguisticObject",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435416",
          "type": "Type",
          "_label": "Description",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300418049",
              "type": "Type",
              "_label": "Brief Text"
            }
          ]
        }
      ],
      "content": "The text and image are primarily red and black"
    }
  ],
  "represents": [
    {
      "id": "http://vocab.getty.edu/aat/300025943",
      "type": "Type",
      "_label": "Woman"
    }
  ]
}

=== linked-art/linked.art/docs/example/visual/spring/2.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/visual/spring/2",
  "type": "VisualItem",
  "_label": "Visual Content of Spring",
  "about": [
    {
      "id": "http://vocab.getty.edu/aat/300133097",
      "type": "Type",
      "_label": "Spring (season)"
    }
  ]
}

=== linked-art/linked.art/docs/example/visual/spring/4.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/visual/spring/4",
  "type": "VisualItem",
  "_label": "Visual Content of Spring",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300015637",
      "type": "Type",
      "_label": "Portrait"
    }
  ]
}

=== linked-art/linked.art/docs/example/visual/nightwatch/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/visual/nightwatch/1",
  "type": "VisualItem",
  "_label": "Visual Content of Night Watch",
  "referred_to_by": [
    {
      "type": "LinguisticObject",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435434",
          "type": "Type",
          "_label": "Copyright/License Statement",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300418049",
              "type": "Type",
              "_label": "Brief Text"
            }
          ]
        }
      ],
      "content": "Public Domain"
    }
  ]
}

=== linked-art/linked.art/docs/example/visual/nightwatch/40.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/visual/nightwatch/40",
  "type": "VisualItem",
  "_label": "Appearance of Night Watch",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300021147",
      "type": "Type",
      "_label": "Baroque",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300015646",
          "type": "Type",
          "_label": "Style"
        }
      ]
    }
  ]
}

=== linked-art/linked.art/docs/example/visual/nightwatch/2.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/visual/nightwatch/2",
  "type": "VisualItem",
  "_label": "Visual Content of Night Watch",
  "subject_to": [
    {
      "type": "Right",
      "_label": "Night Watch's Public Domain status",
      "classified_as": [
        {
          "id": "https://creativecommons.org/publicdomain/zero/1.0/",
          "type": "Type",
          "_label": "Public Domain"
        }
      ],
      "identified_by": [
        {
          "type": "Name",
          "content": "Public Domain"
        }
      ]
    }
  ]
}
