=== linked-art/linked.art/docs/api/1.0/schema/object.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://linked.art/api/1.0/schema/object.json",
	"title": "Human-Made Object Schema",
	"description": "_crm:E22\\_Human-Made\\_Object_\nA human-made object, part thereof, or a natural object with value imbued through interaction with human culture.\nSee: [API](https://linked.art/api/1.0/endpoint/object/) | [Model](https://linked.art/model/object/)",	
	"type": "object",
	"properties": {
		"@context": {"$ref": "core.json#/definitions/ContextStringOrArray"},
		"id": {"$ref": "core.json#/definitions/idProp"},				
		"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
			{"title": "Specific", "type": "string", "const": "HumanMadeObject"}]},
		"_label": {"$ref": "core.json#/definitions/labelProp"},
		"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
		"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
		"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},
		"equivalent": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/equivalentProp"}, 
			{"title": "Specific", "description": "List of `HumanMadeObject` entities", "type": "array", "items": {"$ref": "core.json#/definitions/HumanMadeObjectRef"}}]},
		"representation": {"$ref": "core.json#/definitions/representationProp"},
		"member_of": {"$ref": "core.json#/definitions/member_ofSetProp"},
		"subject_of": {"$ref": "core.json#/definitions/subject_ofProp"},
		"attributed_by": {"$ref": "core.json#/definitions/attributed_byRelProp"},

		"dimension": {"$ref": "core.json#/definitions/dimensionProp"},
		"made_of": {"$ref": "core.json#/definitions/made_ofProp"},
		"part_of": {"title": "crm:P46i_forms_part_of", "description": "Another Human-Made Object of which this Object is part", "$ref": "core.json#/definitions/HumanMadeObjectRef"},

		"current_owner": {"$ref": "core.json#/definitions/current_ownerProp"},
		"current_custodian": {"$ref": "core.json#/definitions/current_custodianProp"},
		"current_permanent_custodian": {"$ref": "core.json#/definitions/current_permanent_custodianProp"},
		"current_location": {"$ref": "core.json#/definitions/current_locationProp"},
		"used_for": {"$ref": "core.json#/definitions/used_forProp"},
		"shows": {"$ref": "core.json#/definitions/showsProp"},
		"carries": {"$ref": "core.json#/definitions/carriesProp"},

		"produced_by": {
			"title": "crm:P108i_was_produced_by",
			"description": "The `Production` activity which created this object",
			"$ref": "#/definitions/Production"},
		"destroyed_by": {
			"title": "crm:P13i_was_destroyed_by",
			"description": "The `Destruction` event in which this object was destroyed",
			"$ref": "#/definitions/Destruction"},
		"removed_by": {
			"title": "crm:P113i_was_removed_by",
			"description": "One or more `PartRemoval` activities in which this object was removed from another object",
			"type": "array", 
			"items": {"$ref": "#/definitions/PartRemoval"}},
		"encountered_by": {
			"title": "sci:O19i_was_object_encountered_at",
			"description": "One or more Encounter activities in which this object was encountered",
			"type": "array",
			"items": {"$ref": "#/definitions/Encounter"}}
	},

	"definitions": {
		"Production": {
			"title": "crm:E12_Production",
			"description": "The production/creation of the object",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
					{"title": "Specific", "type": "string", "const": "Production"}]},
				"_label": {"$ref": "core.json#/definitions/labelProp"},
				"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
				"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},

				"took_place_at": {"$ref": "core.json#/definitions/took_place_atProp"},
				"timespan": {"$ref": "core.json#/definitions/timespanProp"},
				"caused_by": {"$ref": "core.json#/definitions/caused_byProp"},
				"carried_out_by": {"$ref": "core.json#/definitions/carried_out_byProp"},
				"used_specific_object": {"$ref": "core.json#/definitions/used_specific_objectProp"},
				"influenced_by": {"$ref": "core.json#/definitions/influenced_byProp"},
				"technique": {"$ref": "core.json#/definitions/techniqueProp"},
				"part_of": {"title": "crm:P9i_forms_part_of", "description": "An identified event or activity which this activity is part of", "$ref": "core.json#/definitions/EventRefOrActivityRef"},
				"part": {"title":"crm:P46_is_composed_of", "description": "", "type": "array", "items": {"$ref": "#/definitions/Production"}}
			}
		},
		"Destruction": {
			"title": "crm:E6_Destruction",
			"description": "The destruction of the object (separate from any cause of that end of existence)",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
					{"title": "Specific", "type": "string", "const": "Destruction"}]},
				"_label": {"$ref": "core.json#/definitions/labelProp"},
				"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
				"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},
				"took_place_at": {"$ref": "core.json#/definitions/took_place_atProp"},
				"timespan": {"$ref": "core.json#/definitions/timespanProp"},
				"caused_by": {"$ref": "core.json#/definitions/caused_byProp"},
				"part_of": {"title": "crm:P9i_forms_part_of", "description": "An identified event or activity which this event is part of", "$ref": "core.json#/definitions/EventRefOrActivityRef"}
			}
		},
		"PartRemoval": {
			"title": "crm:E80_Part_Removal",
			"description": "The activity of removing this object from some other object.",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
					{"title": "Specific", "type": "string", "const": "PartRemoval"}]},
				"_label": {"$ref": "core.json#/definitions/labelProp"},
				"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
				"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},
				"took_place_at": {"$ref": "core.json#/definitions/took_place_atProp"},
				"timespan": {"$ref": "core.json#/definitions/timespanProp"},
				"caused_by": {"$ref": "core.json#/definitions/caused_byProp"},
				"carried_out_by": {"$ref": "core.json#/definitions/carried_out_byProp"},
				"used_specific_object": {"$ref": "core.json#/definitions/used_specific_objectProp"},
				"influenced_by": {"$ref": "core.json#/definitions/influenced_byProp"},
				"technique": {"$ref": "core.json#/definitions/techniqueProp"},
				"part_of": {"title": "crm:P9i_forms_part_of", "description": "An identified event or activity which this activity is part of", "$ref": "core.json#/definitions/EventRefOrActivityRef"},
				"diminished": {"title": "crm:P112_diminished", "description": "A reference to the object which the object was removed from", "$ref": "core.json#/definitions/HumanMadeObjectRef"}
			}
		},
		"Encounter": {
			"title": "sci:S19_Encounter_Event",
			"description": "The activity during which this object was encountered, found or discovered.",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
					{"title": "Specific", "type": "string", "const": "Encounter"}]},
				"_label": {"$ref": "core.json#/definitions/labelProp"},
				"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
				"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},
				"took_place_at": {"$ref": "core.json#/definitions/took_place_atProp"},
				"timespan": {"$ref": "core.json#/definitions/timespanProp"},
				"caused_by": {"$ref": "core.json#/definitions/caused_byProp"},
				"carried_out_by": {"$ref": "core.json#/definitions/carried_out_byProp"},
				"used_specific_object": {"$ref": "core.json#/definitions/used_specific_objectProp"},
				"influenced_by": {"$ref": "core.json#/definitions/influenced_byProp"},
				"technique": {"$ref": "core.json#/definitions/techniqueProp"},
				"part_of": {"title": "crm:P9i_forms_part_of", "description": "An identified event or activity which this activity is part of", "$ref": "core.json#/definitions/EventRefOrActivityRef"}				
			}
		}				
	},
	"required": ["@context", "id", "type", "_label"],
	"additionalProperties": false
}

=== linked-art/linked.art/docs/example/object/4.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/object/4",
  "type": "HumanMadeObject",
  "_label": "Mona Lisa",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300033618",
      "type": "Type",
      "_label": "Painting",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435443",
          "type": "Type",
          "_label": "Type of Work"
        }
      ]
    }
  ],
  "produced_by": {
    "type": "Production",
    "technique": [
      {
        "id": "http://vocab.getty.edu/aat/300054216",
        "type": "Type",
        "_label": "Painting Technique"
      }
    ],
    "timespan": {
      "type": "TimeSpan",
      "identified_by": [
        {
          "type": "Name",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300404669",
              "type": "Type",
              "_label": "Display Title"
            }
          ],
          "content": "1503-1506"
        }
      ],
      "begin_of_the_begin": "1503-01-01T00:00:00Z",
      "end_of_the_end": "1506-12-31T23:59:59Z"
    },
    "took_place_at": [
      {
        "id": "http://vocab.getty.edu/tgn/7000457",
        "type": "Place",
        "_label": "Florence, Italy"
      }
    ],
    "carried_out_by": [
      {
        "id": "http://vocab.getty.edu/ulan/500010879",
        "type": "Person",
        "_label": "Leonardo da Vinci"
      }
    ],
    "influenced_by": [
      {
        "id": "http://vocab.getty.edu/ulan/500341678",
        "type": "Person",
        "_label": "Lisa del Giocondo"
      }
    ]
  }
}

=== linked-art/linked.art/docs/example/object/yiadom-boakye/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/object/yiadom-boakye/1",
  "type": "HumanMadeObject",
  "_label": "Portrait of Lynette Yiadom-Boakye",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300033618",
      "type": "Type",
      "_label": "Painting",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435443",
          "type": "Type",
          "_label": "Type of Work"
        }
      ]
    }
  ],
  "identified_by": [
    {
      "type": "Identifier",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300312355",
          "type": "Type",
          "_label": "Accession Number"
        }
      ],
      "content": "2021.25.1",
      "assigned_by": [
        {
          "type": "AttributeAssignment",
          "carried_out_by": [
            {
              "id": "https://linked.art/example/group/yuag",
              "type": "Group",
              "_label": "Yale University Art Gallery",
              "classified_as": [
                {
                  "id": "http://vocab.getty.edu/aat/300312281",
                  "type": "Type",
                  "_label": "Museum"
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "type": "Identifier",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300312355",
          "type": "Type",
          "_label": "Accession Number"
        }
      ],
      "content": "B2021.5",
      "assigned_by": [
        {
          "type": "AttributeAssignment",
          "carried_out_by": [
            {
              "id": "https://linked.art/example/group/ycba",
              "type": "Group",
              "_label": "Yale Center for British Art",
              "classified_as": [
                {
                  "id": "http://vocab.getty.edu/aat/300312281",
                  "type": "Type",
                  "_label": "Museum"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}

=== linked-art/linked.art/docs/example/object/nuveen/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/object/nuveen/1",
  "type": "HumanMadeObject",
  "_label": "Nuveen Painting",
  "identified_by": [
    {
      "type": "Name",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300404670",
          "type": "Type",
          "_label": "Primary Name"
        }
      ],
      "content": "The Nuveen Painting"
    }
  ],
  "produced_by": {
    "type": "Production",
    "carried_out_by": [
      {
        "id": "https://linked.art/example/person/dine",
        "type": "Person",
        "_label": "Jim Dine"
      }
    ],
    "caused_by": [
      {
        "id": "https://linked.art/example/event/nuveen_commission",
        "type": "Activity",
        "_label": "Commission"
      }
    ]
  }
}

=== linked-art/linked.art/docs/example/object/spring/11.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/object/spring/11",
  "type": "HumanMadeObject",
  "_label": "Jeanne (Spring) by Manet",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300033618",
      "type": "Type",
      "_label": "Painting",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435443",
          "type": "Type",
          "_label": "Type of Work"
        }
      ]
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "content": "Jeanne (Spring)"
    }
  ],
  "representation": [
    {
      "type": "VisualItem",
      "digitally_shown_by": [
        {
          "type": "DigitalObject",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300215302",
              "type": "Type",
              "_label": "Digital Image"
            }
          ],
          "access_point": [
            {
              "id": "https://media.getty.edu/iiif/image/8094f61e-e458-42bd-90cf-a0ed0dcc90b9/full/full/0/default.jpg",
              "type": "DigitalObject"
            }
          ],
          "digitally_available_via": [
            {
              "type": "DigitalService",
              "access_point": [
                {
                  "id": "https://media.getty.edu/iiif/image/8094f61e-e458-42bd-90cf-a0ed0dcc90b9",
                  "type": "DigitalObject"
                }
              ],
              "conforms_to": [
                {
                  "id": "http://iiif.io/api/image",
                  "type": "InformationObject"
                }
              ],
              "format": "application/ld+json;profile='http://iiif.io/api/image/3/context.json'"
            }
          ]
        }
      ]
    }
  ]
}

=== linked-art/linked.art/docs/example/object/nightwatch/13.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/object/nightwatch/13",
  "type": "HumanMadeObject",
  "_label": "Night Watch by Rembrandt",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300033618",
      "type": "Type",
      "_label": "Painting",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435443",
          "type": "Type",
          "_label": "Type of Work"
        }
      ]
    }
  ],
  "referred_to_by": [
    {
      "type": "LinguisticObject",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435429",
          "type": "Type",
          "_label": "Material Statement",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300418049",
              "type": "Type",
              "_label": "Brief Text"
            }
          ]
        }
      ],
      "content": "Oil on Canvas"
    }
  ]
}

=== linked-art/linked.art/docs/example/object/14.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/object/14",
  "type": "HumanMadeObject",
  "_label": "Painting: Pasture and Sheep",
  "identified_by": [
    {
      "type": "Identifier",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300312355",
          "type": "Type",
          "_label": "Accession Number"
        }
      ],
      "content": "P1998-27"
    },
    {
      "type": "Name",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300404670",
          "type": "Type",
          "_label": "Primary Name"
        }
      ],
      "content": "Pasture and Sheep"
    }
  ]
}

=== linked-art/linked.art/docs/example/object/nightwatch/11.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/object/nightwatch/11",
  "type": "HumanMadeObject",
  "_label": "Night Watch by Rembrandt",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300033618",
      "type": "Type",
      "_label": "Painting",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435443",
          "type": "Type",
          "_label": "Type of Work"
        }
      ]
    },
    {
      "id": "http://vocab.getty.edu/aat/300311843",
      "type": "Type",
      "_label": "Oblong",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300056273",
          "type": "Type",
          "_label": "Shape"
        }
      ]
    }
  ]
}

=== linked-art/linked.art/docs/example/object/spring/13.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/object/spring/13",
  "type": "HumanMadeObject",
  "_label": "Jeanne (Spring) by Manet",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300033618",
      "type": "Type",
      "_label": "Painting",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435443",
          "type": "Type",
          "_label": "Type of Work"
        }
      ]
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "content": "Jeanne (Spring)"
    }
  ],
  "member_of": [
    {
      "id": "https://linked.art/example/set/exhset",
      "type": "Set"
    }
  ]
}
