=== linked-art/linked.art/docs/api/1.0/schema/object.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://linked.art/api/1.0/schema/object.json",
	"title": "Human-Made Object Schema",
	"description": "_crm:E22\\_Human-Made\\_Object_\nA human-made object, part thereof, or a natural object with value imbued through interaction with human culture.\nSee: [API](https://linked.art/api/1.0/endpoint/object/) | [Model](https://linked.art/model/object/)",	
	"type": "object",
	"properties": {
		"@context": {"$ref": "core.json#/definitions/ContextStringOrArray"},
		"id": {"$ref": "core.json#/definitions/idProp"},				
		"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
			{"title": "Specific", "type": "string", "const": "HumanMadeObject"}]},
		"_label": {"$ref": "core.json#/definitions/labelProp"},
		"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
		"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
		"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},
		"equivalent": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/equivalentProp"}, 
			{"title": "Specific", "description": "List of `HumanMadeObject` entities", "type": "array", "items": {"$ref": "core.json#/definitions/HumanMadeObjectRef"}}]},
		"representation": {"$ref": "core.json#/definitions/representationProp"},
		"member_of": {"$ref": "core.json#/definitions/member_ofSetProp"},
		"subject_of": {"$ref": "core.json#/definitions/subject_ofProp"},
		"attributed_by": {"$ref": "core.json#/definitions/attributed_byRelProp"},

		"dimension": {"$ref": "core.json#/definitions/dimensionProp"},
		"made_of": {"$ref": "core.json#/definitions/made_ofProp"},
		"part_of": {"title": "crm:P46i_forms_part_of", "description": "Another Human-Made Object of which this Object is part", "$ref": "core.json#/definitions/HumanMadeObjectRef"},

		"current_owner": {"$ref": "core.json#/definitions/current_ownerProp"},
		"current_custodian": {"$ref": "core.json#/definitions/current_custodianProp"},
		"current_permanent_custodian": {"$ref": "core.json#/definitions/current_permanent_custodianProp"},
		"current_location": {"$ref": "core.json#/definitions/current_locationProp"},
		"used_for": {"$ref": "core.json#/definitions/used_forProp"},
		"shows": {"$ref": "core.json#/definitions/showsProp"},
		"carries": {"$ref": "core.json#/definitions/carriesProp"},

		"produced_by": {
			"title": "crm:P108i_was_produced_by",
			"description": "The `Production` activity which created this object",
			"$ref": "#/definitions/Production"},
		"destroyed_by": {
			"title": "crm:P13i_was_destroyed_by",
			"description": "The `Destruction` event in which this object was destroyed",
			"$ref": "#/definitions/Destruction"},
		"removed_by": {
			"title": "crm:P113i_was_removed_by",
			"description": "One or more `PartRemoval` activities in which this object was removed from another object",
			"type": "array", 
			"items": {"$ref": "#/definitions/PartRemoval"}},
		"encountered_by": {
			"title": "sci:O19i_was_object_encountered_at",
			"description": "One or more Encounter activities in which this object was encountered",
			"type": "array",
			"items": {"$ref": "#/definitions/Encounter"}}
	},

	"definitions": {
		"Production": {
			"title": "crm:E12_Production",
			"description": "The production/creation of the object",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
					{"title": "Specific", "type": "string", "const": "Production"}]},
				"_label": {"$ref": "core.json#/definitions/labelProp"},
				"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
				"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},

				"took_place_at": {"$ref": "core.json#/definitions/took_place_atProp"},
				"timespan": {"$ref": "core.json#/definitions/timespanProp"},
				"caused_by": {"$ref": "core.json#/definitions/caused_byProp"},
				"carried_out_by": {"$ref": "core.json#/definitions/carried_out_byProp"},
				"used_specific_object": {"$ref": "core.json#/definitions/used_specific_objectProp"},
				"influenced_by": {"$ref": "core.json#/definitions/influenced_byProp"},
				"technique": {"$ref": "core.json#/definitions/techniqueProp"},
				"part_of": {"title": "crm:P9i_forms_part_of", "description": "An identified event or activity which this activity is part of", "$ref": "core.json#/definitions/EventRefOrActivityRef"},
				"part": {"title":"crm:P46_is_composed_of", "description": "", "type": "array", "items": {"$ref": "#/definitions/Production"}}
			}
		},
		"Destruction": {
			"title": "crm:E6_Destruction",
			"description": "The destruction of the object (separate from any cause of that end of existence)",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
					{"title": "Specific", "type": "string", "const": "Destruction"}]},
				"_label": {"$ref": "core.json#/definitions/labelProp"},
				"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
				"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},
				"took_place_at": {"$ref": "core.json#/definitions/took_place_atProp"},
				"timespan": {"$ref": "core.json#/definitions/timespanProp"},
				"caused_by": {"$ref": "core.json#/definitions/caused_byProp"},
				"part_of": {"title": "crm:P9i_forms_part_of", "description": "An identified event or activity which this event is part of", "$ref": "core.json#/definitions/EventRefOrActivityRef"}
			}
		},
		"PartRemoval": {
			"title": "crm:E80_Part_Removal",
			"description": "The activity of removing this object from some other object.",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
					{"title": "Specific", "type": "string", "const": "PartRemoval"}]},
				"_label": {"$ref": "core.json#/definitions/labelProp"},
				"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
				"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},
				"took_place_at": {"$ref": "core.json#/definitions/took_place_atProp"},
				"timespan": {"$ref": "core.json#/definitions/timespanProp"},
				"caused_by": {"$ref": "core.json#/definitions/caused_byProp"},
				"carried_out_by": {"$ref": "core.json#/definitions/carried_out_byProp"},
				"used_specific_object": {"$ref": "core.json#/definitions/used_specific_objectProp"},
				"influenced_by": {"$ref": "core.json#/definitions/influenced_byProp"},
				"technique": {"$ref": "core.json#/definitions/techniqueProp"},
				"part_of": {"title": "crm:P9i_forms_part_of", "description": "An identified event or activity which this activity is part of", "$ref": "core.json#/definitions/EventRefOrActivityRef"},
				"diminished": {"title": "crm:P112_diminished", "description": "A reference to the object which the object was removed from", "$ref": "core.json#/definitions/HumanMadeObjectRef"}
			}
		},
		"Encounter": {
			"title": "sci:S19_Encounter_Event",
			"description": "The activity during which this object was encountered, found or discovered.",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
					{"title": "Specific", "type": "string", "const": "Encounter"}]},
				"_label": {"$ref": "core.json#/definitions/labelProp"},
				"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
				"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},
				"took_place_at": {"$ref": "core.json#/definitions/took_place_atProp"},
				"timespan": {"$ref": "core.json#/definitions/timespanProp"},
				"caused_by": {"$ref": "core.json#/definitions/caused_byProp"},
				"carried_out_by": {"$ref": "core.json#/definitions/carried_out_byProp"},
				"used_specific_object": {"$ref": "core.json#/definitions/used_specific_objectProp"},
				"influenced_by": {"$ref": "core.json#/definitions/influenced_byProp"},
				"technique": {"$ref": "core.json#/definitions/techniqueProp"},
				"part_of": {"title": "crm:P9i_forms_part_of", "description": "An identified event or activity which this activity is part of", "$ref": "core.json#/definitions/EventRefOrActivityRef"}				
			}
		}				
	},
	"required": ["@context", "id", "type", "_label"],
	"additionalProperties": false
}

=== linked-art/linked.art/docs/example/object/coppa/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/object/coppa/1",
  "type": "HumanMadeObject",
  "_label": "Coppa Amatoria",
  "identified_by": [
    {
      "type": "Name",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300404670",
          "type": "Type",
          "_label": "Primary Name"
        }
      ],
      "content": "Coppa Amatoria"
    }
  ],
  "produced_by": {
    "type": "Production",
    "carried_out_by": [
      {
        "id": "https://linked.art/example/group/unknown_italian",
        "type": "Group",
        "_label": "Unidentified Italian"
      }
    ]
  }
}

=== linked-art/linked.art/docs/example/object/spring/4.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/object/spring/4",
  "type": "HumanMadeObject",
  "_label": "Jeanne (Spring) by Manet",
  "produced_by": {
    "type": "Production",
    "timespan": {
      "type": "TimeSpan",
      "_label": "1881",
      "begin_of_the_begin": "1881-01-01T00:00:00Z",
      "end_of_the_end": "1881-12-31T23:59:59Z"
    },
    "took_place_at": [
      {
        "id": "https://linked.art/example/place/france",
        "type": "Place",
        "_label": "France"
      }
    ],
    "carried_out_by": [
      {
        "id": "https://linked.art/example/person/manet",
        "type": "Person",
        "_label": "Manet"
      }
    ],
    "during": [
      {
        "id": "https://linked.art/example/event/19c",
        "type": "Period",
        "_label": "19th Century"
      }
    ]
  }
}

=== linked-art/linked.art/docs/example/object/spring/support.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/object/spring/support",
  "type": "HumanMadeObject",
  "_label": "Support of Spring",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300014844",
      "type": "Type",
      "_label": "Support",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300241583",
          "type": "Type",
          "_label": "Part Type"
        }
      ]
    }
  ],
  "referred_to_by": [
    {
      "type": "LinguisticObject",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435429",
          "type": "Type",
          "_label": "Material Statement",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300418049",
              "type": "Type",
              "_label": "Brief Text"
            }
          ]
        }
      ],
      "content": "Canvas"
    }
  ],
  "part_of": [
    {
      "id": "https://linked.art/example/object/spring",
      "type": "HumanMadeObject",
      "_label": "Jeanne (Spring) by Manet"
    }
  ]
}

=== linked-art/linked.art/docs/example/object/nightwatch/57.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/object/nightwatch/57",
  "type": "HumanMadeObject",
  "_label": "The Night Watch",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300033618",
      "type": "Type",
      "_label": "Painting",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435443",
          "type": "Type",
          "_label": "Type of Work"
        }
      ]
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300404670",
          "type": "Type",
          "_label": "Primary Name"
        }
      ],
      "content": "The Night Watch"
    }
  ],
  "attributed_by": [
    {
      "type": "AttributeAssignment",
      "identified_by": [
        {
          "type": "Name",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300404669",
              "type": "Type",
              "_label": "Display Title"
            }
          ],
          "content": "Related Object"
        }
      ],
      "assigned": [
        {
          "id": "https://linked.art/example/object/rppob-28-106",
          "type": "HumanMadeObject",
          "_label": "Nachtwacht"
        }
      ]
    }
  ]
}

=== linked-art/linked.art/docs/example/object/spring/29.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/object/spring/29",
  "type": "HumanMadeObject",
  "_label": "Spring",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300033618",
      "type": "Type",
      "_label": "Painting",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435443",
          "type": "Type",
          "_label": "Type of Work"
        }
      ]
    }
  ],
  "dimension": [
    {
      "type": "Dimension",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300055644",
          "type": "Type",
          "_label": "Height"
        }
      ],
      "value": 74,
      "unit": {
        "id": "http://vocab.getty.edu/aat/300379098",
        "type": "MeasurementUnit",
        "_label": "centimeters"
      },
      "assigned_by": [
        {
          "type": "AttributeAssignment",
          "_label": "Unframed Measuring",
          "technique": [
            {
              "id": "https://linked.art/example/concept/measuring_unframed",
              "type": "Type",
              "_label": "Unframed Measuring"
            }
          ]
        }
      ]
    },
    {
      "type": "Dimension",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300055647",
          "type": "Type",
          "_label": "Width"
        }
      ],
      "value": 51.5,
      "unit": {
        "id": "http://vocab.getty.edu/aat/300379098",
        "type": "MeasurementUnit",
        "_label": "centimeters"
      },
      "assigned_by": [
        {
          "type": "AttributeAssignment",
          "_label": "Unframed Measuring",
          "technique": [
            {
              "id": "https://linked.art/example/concept/measuring_unframed",
              "type": "Type",
              "_label": "Unframed Measuring"
            }
          ]
        }
      ]
    }
  ]
}

=== linked-art/linked.art/docs/example/object/spring/9.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/object/spring/9",
  "type": "HumanMadeObject",
  "_label": "Jeanne (Spring) by Manet",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300033618",
      "type": "Type",
      "_label": "Painting",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435443",
          "type": "Type",
          "_label": "Type of Work"
        }
      ]
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "content": "Jeanne (Spring)"
    }
  ],
  "subject_of": [
    {
      "type": "LinguisticObject",
      "digitally_carried_by": [
        {
          "type": "DigitalObject",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300264578",
              "type": "Type",
              "_label": "Web Page"
            }
          ],
          "format": "text/html",
          "access_point": [
            {
              "id": "https://www.getty.edu/art/collection/object/103QTZ",
              "type": "DigitalObject"
            }
          ]
        }
      ]
    }
  ]
}

=== linked-art/linked.art/docs/example/object/nightwatch/52.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/object/nightwatch/52",
  "type": "HumanMadeObject",
  "_label": "Night Watch by Rembrandt",
  "classified_as": [
    {
      "id": "https://linked.art/example/concept/painting",
      "type": "Type",
      "_label": "Local Copy of Painting",
      "equivalent": [
        {
          "id": "http://vocab.getty.edu/aat/300033618",
          "type": "Type",
          "_label": "painting (visual art)"
        }
      ]
    }
  ]
}

=== linked-art/linked.art/docs/example/object/nightwatch/6.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/object/nightwatch/6",
  "type": "HumanMadeObject",
  "_label": "Night Watch by Rembrandt",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300033618",
      "type": "Type",
      "_label": "Painting",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435443",
          "type": "Type",
          "_label": "Type of Work"
        }
      ]
    }
  ],
  "dimension": [
    {
      "type": "Dimension",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300055647",
          "type": "Type",
          "_label": "Width"
        }
      ],
      "value": 453.5,
      "unit": {
        "id": "http://vocab.getty.edu/aat/300379098",
        "type": "MeasurementUnit",
        "_label": "centimeters"
      }
    },
    {
      "type": "Dimension",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300055644",
          "type": "Type",
          "_label": "Height"
        }
      ],
      "value": 379.5,
      "unit": {
        "id": "http://vocab.getty.edu/aat/300379098",
        "type": "MeasurementUnit",
        "_label": "centimeters"
      }
    }
  ]
}
