=== linked-art/linked.art/docs/api/1.0/schema/place.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://linked.art/api/1.0/schema/place.json",
	"title": "Place Schema",
	"description": "_crm:E53\\_Place_\nGeographic locations where activities occur.\nSee: [API](https://linked.art/api/1.0/endpoint/place/) | [Model](https://linked.art/model/place/)",
	"type": "object",
	"properties": {
		"@context": {"$ref": "core.json#/$defs/ContextStringOrArray"},
		"id": {"$ref": "core.json#/$defs/idProp"},
		"type": {"allOf": [{"title": "General", "$ref": "core.json#/$defs/typeProp"},
			{"title": "Specific", "type": "string", "const": "Place"}]},
		"_label": {"$ref": "core.json#/$defs/labelProp"},
		"classified_as": {"$ref": "core.json#/$defs/classified_asProp"},
		"identified_by": {"$ref": "core.json#/$defs/identified_byProp"},
		"referred_to_by": {"$ref": "core.json#/$defs/referred_to_byProp"},
		"equivalent": {"allOf": [{"title": "General", "$ref": "core.json#/$defs/equivalentProp"},
			{"title": "Specific", "description": "List of `Place` entities", "type": "array", "items": {"$ref": "core.json#/$defs/PlaceRef"}}]},
		"representation": {"$ref": "core.json#/$defs/representationProp"},
		"member_of": {"$ref": "core.json#/$defs/member_ofSetProp"},
		"subject_of": {"$ref": "core.json#/$defs/subject_ofProp"},
		"attributed_by": {"$ref": "core.json#/$defs/attributed_byRelProp"},

		"defined_by": {
			"title": "crm:P168_place_is_defined_by",
			"description": "A string with a WKT or GeoJSON definition of the area of the Place",
			"type": "string"

		},
		"part_of": {
			"title": "crm:P89_falls_within",
			"description": "This `Place` is contained within one or more larger `Place` entities",
			"type": "array", 
			"items": {"$ref": "core.json#/$defs/PlaceRef"}
		}
	},
	"required": ["@context", "id", "type", "_label"],
	"additionalProperties": false
}

=== linked-art/linked.art/docs/example/place/amsterdam/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/place/amsterdam/1",
  "type": "Place",
  "_label": "Amsterdam",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300008389",
      "type": "Type",
      "_label": "City"
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "content": "Amsterdam"
    }
  ],
  "referred_to_by": [
    {
      "type": "LinguisticObject",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435416",
          "type": "Type",
          "_label": "Description",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300418049",
              "type": "Type",
              "_label": "Brief Text"
            }
          ]
        }
      ],
      "content": "Amsterdam is a city in the Netherlands"
    }
  ],
  "part_of": [
    {
      "id": "https://linked.art/example/place/netherlands",
      "type": "Place",
      "_label": "Netherlands",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300128207",
          "type": "Type",
          "_label": "Nation"
        }
      ]
    }
  ]
}

=== linked-art/linked.art/docs/example/place/2.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/place/2",
  "type": "Place",
  "_label": "Los Angeles",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300008389",
      "type": "Type",
      "_label": "City"
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "content": "Los Angeles"
    },
    {
      "type": "Identifier",
      "content": "06-44000"
    }
  ],
  "defined_by": "POLYGON((-118.574 34.185,-117.558 34.185,-117.5585 33.512,-118.574 33.512,-118.5745 34.185))",
  "referred_to_by": [
    {
      "type": "LinguisticObject",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435416",
          "type": "Type",
          "_label": "Description",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300418049",
              "type": "Type",
              "_label": "Brief Text"
            }
          ]
        }
      ],
      "content": "Los Angeles is the largest city in California"
    }
  ],
  "part_of": [
    {
      "type": "Place",
      "_label": "California"
    }
  ],
  "member_of": [
    {
      "type": "Set",
      "_label": "Top 10 Cities in USA"
    }
  ],
  "equivalent": [
    {
      "id": "http://vocab.getty.edu/tgn/7023900",
      "type": "Place",
      "_label": "Los Angeles"
    }
  ]
}

=== linked-art/linked.art/docs/example/place/new_zealand/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/place/new_zealand/1",
  "type": "Place",
  "_label": "New Zealand",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300128207",
      "type": "Type",
      "_label": "Nation"
    }
  ],
  "defined_by": "POLYGON((165.74 -33.55, -179.96 -33.55, -179.96 -47.8, 165.74 -47.8, 165.74 -33.55))"
}

=== linked-art/linked.art/docs/example/place/amsterdam_auction_house/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/place/amsterdam_auction_house/1",
  "type": "Place",
  "_label": "Christie's AMS",
  "identified_by": [
    {
      "type": "Name",
      "content": "Christie's Amsterdam Location"
    }
  ],
  "part_of": [
    {
      "id": "https://linked.art/example/place/amsterdam",
      "type": "Place",
      "_label": "Amsterdam"
    }
  ]
}
