=== linked-art/linked.art/docs/api/1.0/schema/provenance.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://linked.art/api/1.0/schema/provenance.json",
	"title": "Provenance Activity Schema",
	"description": "_crm:E7\\_Activity_\nA broad activity during which the ownership, custody, location or other rights related to one or more objects are changed\nSee: [API](https://linked.art/api/1.0/endpoint/provenance/) | [Model](https://linked.art/model/provenance/)",
	"type": "object",
	"properties": {
		"@context": {"$ref": "core.json#/$defs/ContextStringOrArray"},
		"id": {"$ref": "core.json#/$defs/idProp"},
		"type": {"allOf": [{"title": "General", "$ref": "core.json#/$defs/typeProp"},
			{"title": "Specific", "type": "string", "const": "Activity"}]},
		"_label": {"$ref": "core.json#/$defs/labelProp"},
		"identified_by": {"$ref": "core.json#/$defs/identified_byProp"},
		"classified_as": {"$ref": "core.json#/$defs/classified_asProp"},
		"referred_to_by": {"$ref": "core.json#/$defs/referred_to_byProp"},
		"equivalent": {"allOf": [{"title": "General", "$ref": "core.json#/$defs/equivalentProp"},
			{"title": "Specific", "description": "List of equivalent `Activity` entities", "type": "array", "items": {"$ref": "core.json#/$defs/ActivityRef"}}]},
		"representation": {"$ref": "core.json#/$defs/representationProp"},
		"member_of": {"$ref": "core.json#/$defs/member_ofSetProp"},
		"subject_of": {"$ref": "core.json#/$defs/subject_ofProp"},
		"attributed_by": {"$ref": "core.json#/$defs/attributed_byRelProp"},

		"during": {"$ref": "core.json#/$defs/duringProp"},
		"after": {"$ref": "core.json#/$defs/afterProp"},
		"before": {"$ref": "core.json#/$defs/beforeProp"},

		"took_place_at": {"$ref": "core.json#/$defs/took_place_atProp"},
		"timespan": {"$ref": "core.json#/$defs/timespanProp"},
		"caused_by": {"$ref": "core.json#/$defs/caused_byProp"},
		"carried_out_by": {"$ref": "core.json#/$defs/carried_out_byProp"},
		"used_specific_object": {"$ref": "core.json#/$defs/used_specific_objectProp"},
		"influenced_by": {"$ref": "core.json#/$defs/influenced_byProp"},
		"technique": {"$ref": "core.json#/$defs/techniqueProp"},

		"part_of": {"title": "crm:P9i_forms_part_of", "description": "An identified event or activity which this activity is part of", "$ref": "core.json#/$defs/EventRefOrActivityRef"},
		"part": {"title": "crm:P9_consists_of", "description": "More specific parts of the event", "type": "array", "items": {"$ref": "#/$defs/PartOptions"}}
	},

	"$defs": {
		"PartOptions": {
			"anyOf": [
				{"$ref": "#/$defs/Acquisition"},
				{"$ref": "#/$defs/RightAcquisition"},
				{"$ref": "#/$defs/TransferOfCustody"},
				{"$ref": "#/$defs/Payment"},
				{"$ref": "#/$defs/Encounter"},
				{"$ref": "#/$defs/Move"},
				{"$ref": "#/$defs/Promise"}
			]
		},

		"Acquisition": {
			"title": "crm:E8_Acquisition",
			"description": "The transfer of ownership of a physical object between parties",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/$defs/typeProp"},
					{"title": "Specific", "type": "string", "const": "Acquisition"}]},
				"_label": {"$ref": "core.json#/$defs/labelProp"},
				"identified_by": {"$ref": "core.json#/$defs/identified_byProp"},
				"classified_as": {"$ref": "core.json#/$defs/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/$defs/referred_to_byProp"},
				"took_place_at": {"$ref": "core.json#/$defs/took_place_atProp"},
				"timespan": {"$ref": "core.json#/$defs/timespanProp"},
				"caused_by": {"$ref": "core.json#/$defs/caused_byProp"},
				"carried_out_by": {"$ref": "core.json#/$defs/carried_out_byProp"},
				"used_specific_object": {"$ref": "core.json#/$defs/used_specific_objectProp"},
				"influenced_by": {"$ref": "core.json#/$defs/influenced_byProp"},
				"technique": {"$ref": "core.json#/$defs/techniqueProp"},
				"during": {"$ref": "core.json#/$defs/duringProp"},
				"after": {"$ref": "core.json#/$defs/afterProp"},
				"before": {"$ref": "core.json#/$defs/beforeProp"},

				"transferred_title_from": {"title": "crm:P23_transferred_title_from", "description": "", "type": "array", "items": {"$ref": "core.json#/$defs/PersonRefOrGroupRef"}},
				"transferred_title_to": {"title": "crm:P22_transferred_title_to", "description": "", "type": "array", "items": {"$ref": "core.json#/$defs/PersonRefOrGroupRef"}},
				"transferred_title_of": {"title": "crm:P24_transferred_title_of", "description": "", "type": "array", "items": {"$ref": "core.json#/$defs/HumanMadeObjectRef"}}
			},
			"required": ["type", "transferred_title_of"],
			"additionalProperties": false
		},
		"TransferOfCustody": {
			"title": "crm:E10_Transfer_of_Custody",
			"description": "",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/$defs/typeProp"},
					{"title": "Specific", "type": "string", "const": "TransferOfCustody"}]},
				"_label": {"$ref": "core.json#/$defs/labelProp"},
				"identified_by": {"$ref": "core.json#/$defs/identified_byProp"},
				"classified_as": {"$ref": "core.json#/$defs/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/$defs/referred_to_byProp"},
				"took_place_at": {"$ref": "core.json#/$defs/took_place_atProp"},
				"timespan": {"$ref": "core.json#/$defs/timespanProp"},
				"caused_by": {"$ref": "core.json#/$defs/caused_byProp"},
				"carried_out_by": {"$ref": "core.json#/$defs/carried_out_byProp"},
				"used_specific_object": {"$ref": "core.json#/$defs/used_specific_objectProp"},
				"influenced_by": {"$ref": "core.json#/$defs/influenced_byProp"},
				"technique": {"$ref": "core.json#/$defs/techniqueProp"},
				"during": {"$ref": "core.json#/$defs/duringProp"},
				"after": {"$ref": "core.json#/$defs/afterProp"},
				"before": {"$ref": "core.json#/$defs/beforeProp"},

				"transferred_custody_from": {"title": "crm:P28_custody_surrendered_by", "description": "", "type": "array", "items": {"$ref": "core.json#/$defs/PersonRefOrGroupRef"}},
				"transferred_custody_to": {"title": "crm:P29_custody_received_by", "description": "", "type": "array", "items": {"$ref": "core.json#/$defs/PersonRefOrGroupRef"}},
				"transferred_custody_of": {"title": "crm:P30_transferred_custody_of", "description": "", "type": "array", "items": {"$ref": "core.json#/$defs/HumanMadeObjectRef"}}
			},
			"required": ["type", "transferred_custody_of"],
			"additionalProperties": false			
		},
		"Payment": {
			"title": "la:Payment",
			"description": "",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/$defs/typeProp"},
					{"title": "Specific", "type": "string", "const": "Payment"}]},
				"_label": {"$ref": "core.json#/$defs/labelProp"},
				"identified_by": {"$ref": "core.json#/$defs/identified_byProp"},
				"classified_as": {"$ref": "core.json#/$defs/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/$defs/referred_to_byProp"},
				"took_place_at": {"$ref": "core.json#/$defs/took_place_atProp"},
				"timespan": {"$ref": "core.json#/$defs/timespanProp"},
				"caused_by": {"$ref": "core.json#/$defs/caused_byProp"},
				"carried_out_by": {"$ref": "core.json#/$defs/carried_out_byProp"},
				"used_specific_object": {"$ref": "core.json#/$defs/used_specific_objectProp"},
				"influenced_by": {"$ref": "core.json#/$defs/influenced_byProp"},
				"technique": {"$ref": "core.json#/$defs/techniqueProp"},
				"during": {"$ref": "core.json#/$defs/duringProp"},
				"after": {"$ref": "core.json#/$defs/afterProp"},
				"before": {"$ref": "core.json#/$defs/beforeProp"},

				"paid_from": {"title": "la:paid_from", "description": "", "type": "array", "items": {"$ref": "core.json#/$defs/PersonRefOrGroupRef"}},
				"paid_to": {"title": "la:paid_to", "description": "", "type": "array", "items": {"$ref": "core.json#/$defs/PersonRefOrGroupRef"}},
				"paid_amount": {"title": "la:paid_amount", "description": "", "$ref": "core.json#/$defs/MonetaryAmount"}
			},
			"required": ["type"],
			"additionalProperties": false			
		},
		"RightAcquisition": {
			"title": "la:RightAcquisition",
			"description": "",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/$defs/typeProp"},
					{"title": "Specific", "type": "string", "const": "RightAcquisition"}]},
				"_label": {"$ref": "core.json#/$defs/labelProp"},
				"identified_by": {"$ref": "core.json#/$defs/identified_byProp"},
				"classified_as": {"$ref": "core.json#/$defs/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/$defs/referred_to_byProp"},
				"took_place_at": {"$ref": "core.json#/$defs/took_place_atProp"},
				"timespan": {"$ref": "core.json#/$defs/timespanProp"},
				"caused_by": {"$ref": "core.json#/$defs/caused_byProp"},
				"carried_out_by": {"$ref": "core.json#/$defs/carried_out_byProp"},
				"used_specific_object": {"$ref": "core.json#/$defs/used_specific_objectProp"},
				"influenced_by": {"$ref": "core.json#/$defs/influenced_byProp"},
				"technique": {"$ref": "core.json#/$defs/techniqueProp"},
				"during": {"$ref": "core.json#/$defs/duringProp"},
				"after": {"$ref": "core.json#/$defs/afterProp"},
				"before": {"$ref": "core.json#/$defs/beforeProp"},

				"establishes": {"title": "la:establishes", "description": "", "type": "array", "items": {"$ref": "core.json#/$defs/Right"}},
				"invalidates": {"title": "la:invalidates", "description": "", "type": "array", "items": {"$ref": "core.json#/$defs/Right"}}
			},
			"required": ["type", "establishes"],
			"additionalProperties": false	
		},
		"Move": {
			"title": "crm:E9_Move",
			"description": "",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/$defs/typeProp"},
					{"title": "Specific", "type": "string", "const": "Move"}]},
				"_label": {"$ref": "core.json#/$defs/labelProp"},
				"identified_by": {"$ref": "core.json#/$defs/identified_byProp"},
				"classified_as": {"$ref": "core.json#/$defs/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/$defs/referred_to_byProp"},
				"took_place_at": {"$ref": "core.json#/$defs/took_place_atProp"},
				"timespan": {"$ref": "core.json#/$defs/timespanProp"},
				"caused_by": {"$ref": "core.json#/$defs/caused_byProp"},
				"carried_out_by": {"$ref": "core.json#/$defs/carried_out_byProp"},
				"used_specific_object": {"$ref": "core.json#/$defs/used_specific_objectProp"},
				"influenced_by": {"$ref": "core.json#/$defs/influenced_byProp"},
				"technique": {"$ref": "core.json#/$defs/techniqueProp"},
				"during": {"$ref": "core.json#/$defs/duringProp"},
				"after": {"$ref": "core.json#/$defs/afterProp"},
				"before": {"$ref": "core.json#/$defs/beforeProp"},

				"moved_from": {"title": "crm:P27_moved_from", "description": "Reference to the Place where the objects were moved from", "$ref": "core.json#/$defs/PlaceRef"},
				"moved_to": {"title": "crm:P26_moved_to", "description": "Reference to the Place where the objects were moved to", "$ref": "core.json#/$defs/PlaceRef"},
				"moved": {"title": "crm:P25_moved", "description": "The objects that were moved", "type": "array", "items": {"$ref": "core.json#/$defs/HumanMadeObjectRef"}}
			},
			"required": ["type", "moved"],
			"additionalProperties": false	
		},		
		"Encounter": {
			"title": "sci:S19_Encounter_Event",
			"description": "",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/$defs/typeProp"},
					{"title": "Specific", "type": "string", "const": "Encounter"}]},
				"_label": {"$ref": "core.json#/$defs/labelProp"},
				"identified_by": {"$ref": "core.json#/$defs/identified_byProp"},
				"classified_as": {"$ref": "core.json#/$defs/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/$defs/referred_to_byProp"},
				"took_place_at": {"$ref": "core.json#/$defs/took_place_atProp"},
				"timespan": {"$ref": "core.json#/$defs/timespanProp"},
				"caused_by": {"$ref": "core.json#/$defs/caused_byProp"},
				"carried_out_by": {"$ref": "core.json#/$defs/carried_out_byProp"},
				"used_specific_object": {"$ref": "core.json#/$defs/used_specific_objectProp"},
				"influenced_by": {"$ref": "core.json#/$defs/influenced_byProp"},
				"technique": {"$ref": "core.json#/$defs/techniqueProp"},
				"during": {"$ref": "core.json#/$defs/duringProp"},
				"after": {"$ref": "core.json#/$defs/afterProp"},
				"before": {"$ref": "core.json#/$defs/beforeProp"},

				"encountered": {"title": "sci:O19_has_found_object", "description": "The objects that were encountered during this event", "type": "array", "items": {"$ref": "core.json#/$defs/HumanMadeObjectRef"}}
			},
			"required": ["type", "encountered"],
			"additionalProperties": false	
		},
		"Promise": {
			"title": "crm:E7_Activity",
			"description": "",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/$defs/typeProp"},
					{"title": "Specific", "type": "string", "const": "Activity"}]},
				"_label": {"$ref": "core.json#/$defs/labelProp"},
				"identified_by": {"$ref": "core.json#/$defs/identified_byProp"},
				"classified_as": {"$ref": "core.json#/$defs/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/$defs/referred_to_byProp"},
				"took_place_at": {"$ref": "core.json#/$defs/took_place_atProp"},
				"timespan": {"$ref": "core.json#/$defs/timespanProp"},
				"caused_by": {"$ref": "core.json#/$defs/caused_byProp"},
				"carried_out_by": {"$ref": "core.json#/$defs/carried_out_byProp"},
				"used_specific_object": {"$ref": "core.json#/$defs/used_specific_objectProp"},
				"influenced_by": {"$ref": "core.json#/$defs/influenced_byProp"},
				"technique": {"$ref": "core.json#/$defs/techniqueProp"},
				"during": {"$ref": "core.json#/$defs/duringProp"},
				"after": {"$ref": "core.json#/$defs/afterProp"},
				"before": {"$ref": "core.json#/$defs/beforeProp"}
			},
			"required": ["type", "classified_as"],
			"additionalProperties": false	
		}
	},
	"required": ["@context", "id", "type", "_label", "classified_as"],
	"additionalProperties": false
}

=== linked-art/linked.art/docs/example/provenance/unknown_faure/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/provenance/unknown_faure/1",
  "type": "Activity",
  "_label": "Unknown Acquisition of Spring by Faure",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300055863",
      "type": "Type",
      "_label": "Provenance Activity"
    }
  ],
  "after": [
    {
      "id": "https://linked.art/example/provenance/manet_proust",
      "type": "Activity",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300055863",
          "type": "Type",
          "_label": "Provenance Activity"
        }
      ]
    }
  ],
  "before": [
    {
      "type": "Activity",
      "_label": "foure_durand",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300055863",
          "type": "Type",
          "_label": "Provenance Activity"
        }
      ]
    }
  ]
}

=== linked-art/linked.art/docs/example/provenance/wiley_move/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/provenance/wiley_move/1",
  "type": "Activity",
  "_label": "Movement of Wiley Painting",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300055863",
      "type": "Type",
      "_label": "Provenance Activity"
    }
  ],
  "part": [
    {
      "type": "Move",
      "moved": [
        {
          "id": "https://linked.art/example/object/yiadom-boakye",
          "type": "HumanMadeObject",
          "_label": "Portrait of Lynette Yiadom-Boakye"
        }
      ],
      "moved_from": {
        "id": "https://linked.art/example/place/ycba_gallery",
        "type": "Place",
        "_label": "YCBA Gallery"
      },
      "moved_to": {
        "id": "https://linked.art/example/place/yuag_gallery",
        "type": "Place",
        "_label": "YUAG Gallery"
      }
    }
  ]
}

=== linked-art/linked.art/docs/example/provenance/sharp_sale/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/provenance/sharp_sale/1",
  "type": "Activity",
  "_label": "Purchase of Stolen Painting",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300055863",
      "type": "Type",
      "_label": "Provenance Activity"
    }
  ],
  "part": [
    {
      "type": "TransferOfCustody",
      "_label": "Sale of Painting",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300438484",
          "type": "Type",
          "_label": "sale of stolen goods"
        }
      ],
      "transferred_custody_of": [
        {
          "id": "https://linked.art/example/object/cheyenne",
          "type": "HumanMadeObject",
          "_label": "Cheyenne Oklahoma"
        }
      ],
      "transferred_custody_from": [
        {
          "id": "https://linked.art/example/person/alter",
          "type": "Person",
          "_label": "Jerry Alter"
        }
      ]
    },
    {
      "type": "Payment",
      "paid_amount": {
        "type": "MonetaryAmount",
        "_label": "Payment to Thief",
        "value": 52650,
        "currency": {
          "id": "http://vocab.getty.edu/aat/300411994",
          "type": "Currency",
          "_label": "US Dollars",
          "notation": "USD"
        }
      },
      "paid_to": [
        {
          "id": "https://linked.art/example/person/alter",
          "type": "Person",
          "_label": "Jerry Alter"
        }
      ]
    }
  ]
}

=== linked-art/linked.art/docs/example/provenance/spring_getty/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/provenance/spring_getty/1",
  "type": "Activity",
  "_label": "Return of Spring to Getty",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300055863",
      "type": "Type",
      "_label": "Provenance Activity"
    }
  ],
  "part": [
    {
      "type": "TransferOfCustody",
      "_label": "Return",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300438467",
          "type": "Type",
          "_label": "Return of Loan"
        }
      ],
      "transferred_custody_of": [
        {
          "id": "https://linked.art/example/object/spring",
          "type": "HumanMadeObject",
          "_label": "Spring"
        }
      ],
      "transferred_custody_from": [
        {
          "id": "https://linked.art/example/group/aic",
          "type": "Group",
          "_label": "Art Institute of Chicago"
        }
      ],
      "transferred_custody_to": [
        {
          "id": "https://linked.art/example/group/getty",
          "type": "Group",
          "_label": "Getty Museum"
        }
      ]
    }
  ]
}

=== linked-art/linked.art/docs/example/provenance/ziwei_yuag/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/provenance/ziwei_yuag/1",
  "type": "Activity",
  "_label": "Gift of Landscape to YUAG",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300055863",
      "type": "Type",
      "_label": "Provenance Activity"
    },
    {
      "id": "http://vocab.getty.edu/aat/300417637",
      "type": "Type",
      "_label": "Gift"
    }
  ],
  "timespan": {
    "type": "TimeSpan",
    "begin_of_the_begin": "1999-01-01T00:00:00Z",
    "end_of_the_end": "1999-12-31T23:59:59Z"
  },
  "part": [
    {
      "type": "Acquisition",
      "_label": "Acquisition of Painting 1",
      "transferred_title_of": [
        {
          "id": "https://linked.art/example/object/ziwei_landscape",
          "type": "HumanMadeObject",
          "_label": "Landscape"
        }
      ],
      "transferred_title_from": [
        {
          "id": "https://linked.art/example/person/ziwei",
          "type": "Person",
          "_label": "Xu Ziwei"
        }
      ],
      "transferred_title_to": [
        {
          "id": "https://linked.art/example/group/yuag",
          "type": "Group",
          "_label": "Yale University Art Gallery"
        }
      ]
    }
  ]
}

=== linked-art/linked.art/docs/example/provenance/payneheirs_getty/2.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/provenance/payneheirs_getty/2",
  "type": "Activity",
  "_label": "Purchase of Spring",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300055863",
      "type": "Type",
      "_label": "Provenance Activity"
    }
  ],
  "part": [
    {
      "type": "Acquisition",
      "_label": "Acquisition of Painting",
      "transferred_title_of": [
        {
          "id": "https://linked.art/example/object/spring",
          "type": "HumanMadeObject",
          "_label": "Spring"
        }
      ],
      "transferred_title_from": [
        {
          "id": "https://linked.art/example/group/payne_heirs",
          "type": "Group",
          "_label": "Family of Oliver Payne"
        }
      ],
      "transferred_title_to": [
        {
          "id": "https://linked.art/example/group/getty",
          "type": "Group",
          "_label": "J. Paul Getty Museum"
        }
      ]
    },
    {
      "type": "TransferOfCustody",
      "_label": "Custody by Department",
      "transferred_custody_of": [
        {
          "id": "https://linked.art/example/object/spring",
          "type": "HumanMadeObject",
          "_label": "Spring"
        }
      ],
      "transferred_custody_from": [
        {
          "id": "https://linked.art/example/group/payne_heirs",
          "type": "Group",
          "_label": "Family of Oliver Payne"
        }
      ],
      "transferred_custody_to": [
        {
          "id": "https://linked.art/example/group/getty_ptgs",
          "type": "Group",
          "_label": "Paintings Department"
        }
      ]
    }
  ]
}

=== linked-art/linked.art/docs/example/provenance/5.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/provenance/5",
  "type": "Activity",
  "_label": "Copyright acquisition by PCA",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300055863",
      "type": "Type",
      "_label": "Provenance Activity"
    }
  ],
  "part": [
    {
      "type": "RightAcquisition",
      "establishes": [
        {
          "type": "Right",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300055598",
              "type": "Type",
              "_label": "Copyright"
            }
          ],
          "possessed_by": [
            {
              "type": "Group",
              "_label": "Paintings Copyright Association"
            }
          ],
          "applies_to": [
            {
              "type": "HumanMadeObject",
              "_label": "Painting",
              "classified_as": [
                {
                  "id": "http://vocab.getty.edu/aat/300033618",
                  "type": "Type",
                  "_label": "Painting",
                  "classified_as": [
                    {
                      "id": "http://vocab.getty.edu/aat/300435443",
                      "type": "Type",
                      "_label": "Type of Work"
                    }
                  ]
                },
                {
                  "id": "http://vocab.getty.edu/aat/300133025",
                  "type": "Type",
                  "_label": "Artwork"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}

=== linked-art/linked.art/docs/example/provenance/durand_payne/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/provenance/durand_payne/1",
  "type": "Activity",
  "_label": "Purchase of Spring by Payne",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300055863",
      "type": "Type",
      "_label": "Provenance Activity"
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300404670",
          "type": "Type",
          "_label": "Primary Name"
        }
      ],
      "content": "Purchase of Spring by Payne from Durand-Ruel"
    }
  ],
  "timespan": {
    "type": "TimeSpan",
    "begin_of_the_begin": "1909-01-01T00:00:00Z",
    "end_of_the_end": "1909-12-31T23:59:59Z"
  },
  "part": [
    {
      "type": "Acquisition",
      "_label": "Ownership of Spring to Payne",
      "transferred_title_of": [
        {
          "id": "https://linked.art/example/object/spring",
          "type": "HumanMadeObject",
          "_label": "Spring"
        }
      ],
      "transferred_title_from": [
        {
          "id": "https://linked.art/example/person/durand",
          "type": "Person",
          "_label": "Durand-Ruel Gallery"
        }
      ],
      "transferred_title_to": [
        {
          "id": "https://linked.art/example/person/payne",
          "type": "Person",
          "_label": "Oliver Payne"
        }
      ]
    }
  ]
}
