=== linked-art/linked.art/docs/api/1.0/schema/provenance.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://linked.art/api/1.0/schema/provenance.json",
	"title": "Provenance Activity Schema",
	"description": "_crm:E7\\_Activity_\nA broad activity during which the ownership, custody, location or other rights related to one or more objects are changed\nSee: [API](https://linked.art/api/1.0/endpoint/provenance/) | [Model](https://linked.art/model/provenance/)",
	"type": "object",
	"properties": {
		"@context": {"$ref": "core.json#/$defs/ContextStringOrArray"},
		"id": {"$ref": "core.json#/$defs/idProp"},
		"type": {"allOf": [{"title": "General", "$ref": "core.json#/$defs/typeProp"},
			{"title": "Specific", "type": "string", "const": "Activity"}]},
		"_label": {"$ref": "core.json#/$defs/labelProp"},
		"identified_by": {"$ref": "core.json#/$defs/identified_byProp"},
		"classified_as": {"$ref": "core.json#/$defs/classified_asProp"},
		"referred_to_by": {"$ref": "core.json#/$defs/referred_to_byProp"},
		"equivalent": {"allOf": [{"title": "General", "$ref": "core.json#/$defs/equivalentProp"},
			{"title": "Specific", "description": "List of equivalent `Activity` entities", "type": "array", "items": {"$ref": "core.json#/$defs/ActivityRef"}}]},
		"representation": {"$ref": "core.json#/$defs/representationProp"},
		"member_of": {"$ref": "core.json#/$defs/member_ofSetProp"},
		"subject_of": {"$ref": "core.json#/$defs/subject_ofProp"},
		"attributed_by": {"$ref": "core.json#/$defs/attributed_byRelProp"},

		"during": {"$ref": "core.json#/$defs/duringProp"},
		"after": {"$ref": "core.json#/$defs/afterProp"},
		"before": {"$ref": "core.json#/$defs/beforeProp"},

		"took_place_at": {"$ref": "core.json#/$defs/took_place_atProp"},
		"timespan": {"$ref": "core.json#/$defs/timespanProp"},
		"caused_by": {"$ref": "core.json#/$defs/caused_byProp"},
		"carried_out_by": {"$ref": "core.json#/$defs/carried_out_byProp"},
		"used_specific_object": {"$ref": "core.json#/$defs/used_specific_objectProp"},
		"influenced_by": {"$ref": "core.json#/$defs/influenced_byProp"},
		"technique": {"$ref": "core.json#/$defs/techniqueProp"},

		"part_of": {"title": "crm:P9i_forms_part_of", "description": "An identified event or activity which this activity is part of", "$ref": "core.json#/$defs/EventRefOrActivityRef"},
		"part": {"title": "crm:P9_consists_of", "description": "More specific parts of the event", "type": "array", "items": {"$ref": "#/$defs/PartOptions"}}
	},

	"$defs": {
		"PartOptions": {
			"anyOf": [
				{"$ref": "#/$defs/Acquisition"},
				{"$ref": "#/$defs/RightAcquisition"},
				{"$ref": "#/$defs/TransferOfCustody"},
				{"$ref": "#/$defs/Payment"},
				{"$ref": "#/$defs/Encounter"},
				{"$ref": "#/$defs/Move"},
				{"$ref": "#/$defs/Promise"}
			]
		},

		"Acquisition": {
			"title": "crm:E8_Acquisition",
			"description": "The transfer of ownership of a physical object between parties",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/$defs/typeProp"},
					{"title": "Specific", "type": "string", "const": "Acquisition"}]},
				"_label": {"$ref": "core.json#/$defs/labelProp"},
				"identified_by": {"$ref": "core.json#/$defs/identified_byProp"},
				"classified_as": {"$ref": "core.json#/$defs/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/$defs/referred_to_byProp"},
				"took_place_at": {"$ref": "core.json#/$defs/took_place_atProp"},
				"timespan": {"$ref": "core.json#/$defs/timespanProp"},
				"caused_by": {"$ref": "core.json#/$defs/caused_byProp"},
				"carried_out_by": {"$ref": "core.json#/$defs/carried_out_byProp"},
				"used_specific_object": {"$ref": "core.json#/$defs/used_specific_objectProp"},
				"influenced_by": {"$ref": "core.json#/$defs/influenced_byProp"},
				"technique": {"$ref": "core.json#/$defs/techniqueProp"},
				"during": {"$ref": "core.json#/$defs/duringProp"},
				"after": {"$ref": "core.json#/$defs/afterProp"},
				"before": {"$ref": "core.json#/$defs/beforeProp"},

				"transferred_title_from": {"title": "crm:P23_transferred_title_from", "description": "", "type": "array", "items": {"$ref": "core.json#/$defs/PersonRefOrGroupRef"}},
				"transferred_title_to": {"title": "crm:P22_transferred_title_to", "description": "", "type": "array", "items": {"$ref": "core.json#/$defs/PersonRefOrGroupRef"}},
				"transferred_title_of": {"title": "crm:P24_transferred_title_of", "description": "", "type": "array", "items": {"$ref": "core.json#/$defs/HumanMadeObjectRef"}}
			},
			"required": ["type", "transferred_title_of"],
			"additionalProperties": false
		},
		"TransferOfCustody": {
			"title": "crm:E10_Transfer_of_Custody",
			"description": "",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/$defs/typeProp"},
					{"title": "Specific", "type": "string", "const": "TransferOfCustody"}]},
				"_label": {"$ref": "core.json#/$defs/labelProp"},
				"identified_by": {"$ref": "core.json#/$defs/identified_byProp"},
				"classified_as": {"$ref": "core.json#/$defs/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/$defs/referred_to_byProp"},
				"took_place_at": {"$ref": "core.json#/$defs/took_place_atProp"},
				"timespan": {"$ref": "core.json#/$defs/timespanProp"},
				"caused_by": {"$ref": "core.json#/$defs/caused_byProp"},
				"carried_out_by": {"$ref": "core.json#/$defs/carried_out_byProp"},
				"used_specific_object": {"$ref": "core.json#/$defs/used_specific_objectProp"},
				"influenced_by": {"$ref": "core.json#/$defs/influenced_byProp"},
				"technique": {"$ref": "core.json#/$defs/techniqueProp"},
				"during": {"$ref": "core.json#/$defs/duringProp"},
				"after": {"$ref": "core.json#/$defs/afterProp"},
				"before": {"$ref": "core.json#/$defs/beforeProp"},

				"transferred_custody_from": {"title": "crm:P28_custody_surrendered_by", "description": "", "type": "array", "items": {"$ref": "core.json#/$defs/PersonRefOrGroupRef"}},
				"transferred_custody_to": {"title": "crm:P29_custody_received_by", "description": "", "type": "array", "items": {"$ref": "core.json#/$defs/PersonRefOrGroupRef"}},
				"transferred_custody_of": {"title": "crm:P30_transferred_custody_of", "description": "", "type": "array", "items": {"$ref": "core.json#/$defs/HumanMadeObjectRef"}}
			},
			"required": ["type", "transferred_custody_of"],
			"additionalProperties": false			
		},
		"Payment": {
			"title": "la:Payment",
			"description": "",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/$defs/typeProp"},
					{"title": "Specific", "type": "string", "const": "Payment"}]},
				"_label": {"$ref": "core.json#/$defs/labelProp"},
				"identified_by": {"$ref": "core.json#/$defs/identified_byProp"},
				"classified_as": {"$ref": "core.json#/$defs/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/$defs/referred_to_byProp"},
				"took_place_at": {"$ref": "core.json#/$defs/took_place_atProp"},
				"timespan": {"$ref": "core.json#/$defs/timespanProp"},
				"caused_by": {"$ref": "core.json#/$defs/caused_byProp"},
				"carried_out_by": {"$ref": "core.json#/$defs/carried_out_byProp"},
				"used_specific_object": {"$ref": "core.json#/$defs/used_specific_objectProp"},
				"influenced_by": {"$ref": "core.json#/$defs/influenced_byProp"},
				"technique": {"$ref": "core.json#/$defs/techniqueProp"},
				"during": {"$ref": "core.json#/$defs/duringProp"},
				"after": {"$ref": "core.json#/$defs/afterProp"},
				"before": {"$ref": "core.json#/$defs/beforeProp"},

				"paid_from": {"title": "la:paid_from", "description": "", "type": "array", "items": {"$ref": "core.json#/$defs/PersonRefOrGroupRef"}},
				"paid_to": {"title": "la:paid_to", "description": "", "type": "array", "items": {"$ref": "core.json#/$defs/PersonRefOrGroupRef"}},
				"paid_amount": {"title": "la:paid_amount", "description": "", "$ref": "core.json#/$defs/MonetaryAmount"}
			},
			"required": ["type"],
			"additionalProperties": false			
		},
		"RightAcquisition": {
			"title": "la:RightAcquisition",
			"description": "",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/$defs/typeProp"},
					{"title": "Specific", "type": "string", "const": "RightAcquisition"}]},
				"_label": {"$ref": "core.json#/$defs/labelProp"},
				"identified_by": {"$ref": "core.json#/$defs/identified_byProp"},
				"classified_as": {"$ref": "core.json#/$defs/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/$defs/referred_to_byProp"},
				"took_place_at": {"$ref": "core.json#/$defs/took_place_atProp"},
				"timespan": {"$ref": "core.json#/$defs/timespanProp"},
				"caused_by": {"$ref": "core.json#/$defs/caused_byProp"},
				"carried_out_by": {"$ref": "core.json#/$defs/carried_out_byProp"},
				"used_specific_object": {"$ref": "core.json#/$defs/used_specific_objectProp"},
				"influenced_by": {"$ref": "core.json#/$defs/influenced_byProp"},
				"technique": {"$ref": "core.json#/$defs/techniqueProp"},
				"during": {"$ref": "core.json#/$defs/duringProp"},
				"after": {"$ref": "core.json#/$defs/afterProp"},
				"before": {"$ref": "core.json#/$defs/beforeProp"},

				"establishes": {"title": "la:establishes", "description": "", "type": "array", "items": {"$ref": "core.json#/$defs/Right"}},
				"invalidates": {"title": "la:invalidates", "description": "", "type": "array", "items": {"$ref": "core.json#/$defs/Right"}}
			},
			"required": ["type", "establishes"],
			"additionalProperties": false	
		},
		"Move": {
			"title": "crm:E9_Move",
			"description": "",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/$defs/typeProp"},
					{"title": "Specific", "type": "string", "const": "Move"}]},
				"_label": {"$ref": "core.json#/$defs/labelProp"},
				"identified_by": {"$ref": "core.json#/$defs/identified_byProp"},
				"classified_as": {"$ref": "core.json#/$defs/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/$defs/referred_to_byProp"},
				"took_place_at": {"$ref": "core.json#/$defs/took_place_atProp"},
				"timespan": {"$ref": "core.json#/$defs/timespanProp"},
				"caused_by": {"$ref": "core.json#/$defs/caused_byProp"},
				"carried_out_by": {"$ref": "core.json#/$defs/carried_out_byProp"},
				"used_specific_object": {"$ref": "core.json#/$defs/used_specific_objectProp"},
				"influenced_by": {"$ref": "core.json#/$defs/influenced_byProp"},
				"technique": {"$ref": "core.json#/$defs/techniqueProp"},
				"during": {"$ref": "core.json#/$defs/duringProp"},
				"after": {"$ref": "core.json#/$defs/afterProp"},
				"before": {"$ref": "core.json#/$defs/beforeProp"},

				"moved_from": {"title": "crm:P27_moved_from", "description": "Reference to the Place where the objects were moved from", "$ref": "core.json#/$defs/PlaceRef"},
				"moved_to": {"title": "crm:P26_moved_to", "description": "Reference to the Place where the objects were moved to", "$ref": "core.json#/$defs/PlaceRef"},
				"moved": {"title": "crm:P25_moved", "description": "The objects that were moved", "type": "array", "items": {"$ref": "core.json#/$defs/HumanMadeObjectRef"}}
			},
			"required": ["type", "moved"],
			"additionalProperties": false	
		},		
		"Encounter": {
			"title": "sci:S19_Encounter_Event",
			"description": "",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/$defs/typeProp"},
					{"title": "Specific", "type": "string", "const": "Encounter"}]},
				"_label": {"$ref": "core.json#/$defs/labelProp"},
				"identified_by": {"$ref": "core.json#/$defs/identified_byProp"},
				"classified_as": {"$ref": "core.json#/$defs/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/$defs/referred_to_byProp"},
				"took_place_at": {"$ref": "core.json#/$defs/took_place_atProp"},
				"timespan": {"$ref": "core.json#/$defs/timespanProp"},
				"caused_by": {"$ref": "core.json#/$defs/caused_byProp"},
				"carried_out_by": {"$ref": "core.json#/$defs/carried_out_byProp"},
				"used_specific_object": {"$ref": "core.json#/$defs/used_specific_objectProp"},
				"influenced_by": {"$ref": "core.json#/$defs/influenced_byProp"},
				"technique": {"$ref": "core.json#/$defs/techniqueProp"},
				"during": {"$ref": "core.json#/$defs/duringProp"},
				"after": {"$ref": "core.json#/$defs/afterProp"},
				"before": {"$ref": "core.json#/$defs/beforeProp"},

				"encountered": {"title": "sci:O19_has_found_object", "description": "The objects that were encountered during this event", "type": "array", "items": {"$ref": "core.json#/$defs/HumanMadeObjectRef"}}
			},
			"required": ["type", "encountered"],
			"additionalProperties": false	
		},
		"Promise": {
			"title": "crm:E7_Activity",
			"description": "",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/$defs/typeProp"},
					{"title": "Specific", "type": "string", "const": "Activity"}]},
				"_label": {"$ref": "core.json#/$defs/labelProp"},
				"identified_by": {"$ref": "core.json#/$defs/identified_byProp"},
				"classified_as": {"$ref": "core.json#/$defs/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/$defs/referred_to_byProp"},
				"took_place_at": {"$ref": "core.json#/$defs/took_place_atProp"},
				"timespan": {"$ref": "core.json#/$defs/timespanProp"},
				"caused_by": {"$ref": "core.json#/$defs/caused_byProp"},
				"carried_out_by": {"$ref": "core.json#/$defs/carried_out_byProp"},
				"used_specific_object": {"$ref": "core.json#/$defs/used_specific_objectProp"},
				"influenced_by": {"$ref": "core.json#/$defs/influenced_byProp"},
				"technique": {"$ref": "core.json#/$defs/techniqueProp"},
				"during": {"$ref": "core.json#/$defs/duringProp"},
				"after": {"$ref": "core.json#/$defs/afterProp"},
				"before": {"$ref": "core.json#/$defs/beforeProp"}
			},
			"required": ["type", "classified_as"],
			"additionalProperties": false	
		}
	},
	"required": ["@context", "id", "type", "_label", "classified_as"],
	"additionalProperties": false
}

=== linked-art/linked.art/docs/example/provenance/yuag_ycba_wiley/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/provenance/yuag_ycba_wiley/1",
  "type": "Activity",
  "_label": "Purchase of Painting",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300055863",
      "type": "Type",
      "_label": "Provenance Activity"
    }
  ],
  "timespan": {
    "type": "TimeSpan",
    "begin_of_the_begin": "2021-01-01T00:00:00Z",
    "end_of_the_end": "2021-12-31T23:59:59Z"
  },
  "part": [
    {
      "type": "Acquisition",
      "transferred_title_of": [
        {
          "id": "https://linked.art/example/object/yiadom-boakye",
          "type": "HumanMadeObject",
          "_label": "Portrait of Lynette Yiadom-Boakye"
        }
      ],
      "transferred_title_to": [
        {
          "id": "https://linked.art/example/group/yuag",
          "type": "Group",
          "_label": "Yale University Art Gallery"
        },
        {
          "id": "https://linked.art/example/group/ycba",
          "type": "Group",
          "_label": "Yale Center for British Art"
        }
      ]
    }
  ]
}

=== linked-art/linked.art/docs/example/provenance/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/provenance/1",
  "type": "Activity",
  "_label": "St George from Simpson to Adams",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300055863",
      "type": "Type",
      "_label": "Provenance Activity"
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "content": "Purchase of Lot 0055a, Durer's St George and the Dragon"
    },
    {
      "type": "Identifier",
      "content": "0055a"
    }
  ],
  "timespan": {
    "type": "TimeSpan",
    "_label": "1820 Mar 09",
    "begin_of_the_begin": "1820-03-09T00:00:00Z",
    "end_of_the_end": "1820-03-09T23:59:59Z"
  },
  "took_place_at": [
    {
      "id": "http://vocab.getty.edu/tgn/7011781",
      "type": "Place",
      "_label": "London"
    }
  ],
  "carried_out_by": [
    {
      "id": "http://vocab.getty.edu/ulan/500451765",
      "type": "Group",
      "_label": "Edward Foster & Son"
    }
  ],
  "used_specific_object": [
    {
      "id": "http://example.org/set/Br1908/0055",
      "type": "Set",
      "_label": "Set of Objects for Lot 0055"
    }
  ],
  "caused_by": [
    {
      "id": "http://example.org/auction/Br1908/0055",
      "type": "Activity",
      "_label": "Auction of Lot 0055"
    }
  ],
  "part": [
    {
      "type": "Acquisition",
      "transferred_title_of": [
        {
          "id": "http://example.museum/object/1",
          "type": "HumanMadeObject",
          "_label": "St George and the Dragon"
        }
      ],
      "transferred_title_from": [
        {
          "id": "http://example.museum/person/2",
          "type": "Person",
          "_label": "Simpson"
        }
      ],
      "transferred_title_to": [
        {
          "id": "http://example.museum/person/1",
          "type": "Person",
          "_label": "Adams"
        }
      ]
    },
    {
      "type": "Payment",
      "paid_amount": {
        "type": "MonetaryAmount",
        "_label": "8.8 pounds",
        "value": 8.8,
        "currency": {
          "id": "http://vocab.getty.edu/aat/300411998",
          "type": "Currency",
          "_label": "British Pounds",
          "notation": "GBP"
        }
      },
      "paid_from": [
        {
          "id": "http://example.museum/person/1",
          "type": "Person",
          "_label": "Adams"
        }
      ],
      "paid_to": [
        {
          "id": "http://example.museum/person/2",
          "type": "Person",
          "_label": "Simpson"
        }
      ]
    }
  ]
}

=== linked-art/linked.art/docs/example/provenance/spring_aic/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/provenance/spring_aic/1",
  "type": "Activity",
  "_label": "Loan of Spring to AIC",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300055863",
      "type": "Type",
      "_label": "Provenance Activity"
    }
  ],
  "part": [
    {
      "type": "TransferOfCustody",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300417645",
          "type": "Type",
          "_label": "Loan"
        }
      ],
      "transferred_custody_of": [
        {
          "id": "https://linked.art/example/object/spring",
          "type": "HumanMadeObject",
          "_label": "Spring"
        }
      ],
      "transferred_custody_from": [
        {
          "id": "https://linked.art/example/group/getty",
          "type": "Group",
          "_label": "Getty Museum"
        }
      ],
      "transferred_custody_to": [
        {
          "id": "https://linked.art/example/group/aic",
          "type": "Group",
          "_label": "Art Institute of Chicago"
        }
      ]
    }
  ]
}

=== linked-art/linked.art/docs/example/provenance/mona_lisa_theft/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/provenance/mona_lisa_theft/1",
  "type": "Activity",
  "_label": "Theft of Mona Lisa",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300055863",
      "type": "Type",
      "_label": "Provenance Activity"
    }
  ],
  "part": [
    {
      "type": "TransferOfCustody",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300055292",
          "type": "Type",
          "_label": "Theft"
        }
      ],
      "transferred_custody_of": [
        {
          "id": "https://linked.art/example/object/monalisa",
          "type": "HumanMadeObject",
          "_label": "Mona Lisa"
        }
      ],
      "transferred_custody_from": [
        {
          "id": "https://linked.art/example/group/louvre",
          "type": "Group",
          "_label": "Louvre"
        }
      ],
      "transferred_custody_to": [
        {
          "id": "https://linked.art/example/person/peruggia",
          "type": "Person",
          "_label": "Vincenzo Peruggia"
        }
      ]
    }
  ]
}

=== linked-art/linked.art/docs/example/provenance/fixme/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/provenance/fixme/1",
  "type": "Activity",
  "_label": "Purchase of Sculpture with Commission",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300055863",
      "type": "Type",
      "_label": "Provenance Activity"
    }
  ],
  "part": [
    {
      "type": "Payment",
      "paid_amount": {
        "type": "MonetaryAmount",
        "value": 900,
        "currency": {
          "id": "http://vocab.getty.edu/aat/300411994",
          "type": "Currency",
          "_label": "US Dollars",
          "notation": "USD"
        }
      },
      "paid_from": [
        {
          "type": "Person",
          "_label": "Buyer"
        }
      ],
      "paid_to": [
        {
          "type": "Person",
          "_label": "Seller"
        }
      ]
    },
    {
      "type": "Payment",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300393199",
          "type": "Type",
          "_label": "Commission"
        }
      ],
      "paid_amount": {
        "type": "MonetaryAmount",
        "value": 100,
        "currency": {
          "id": "http://vocab.getty.edu/aat/300411994",
          "type": "Currency",
          "_label": "US Dollars"
        }
      },
      "paid_from": [
        {
          "type": "Person",
          "_label": "Buyer"
        }
      ],
      "paid_to": [
        {
          "type": "Group",
          "_label": "Auction House",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300417515",
              "type": "Type",
              "_label": "Auction House (organization)"
            }
          ]
        }
      ]
    }
  ]
}

=== linked-art/linked.art/docs/example/provenance/payneheirs_getty/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/provenance/payneheirs_getty/1",
  "type": "Activity",
  "_label": "Purchase of Spring for Getty",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300055863",
      "type": "Type",
      "_label": "Provenance Activity"
    }
  ],
  "part": [
    {
      "type": "Acquisition",
      "_label": "Acquisition of Spring",
      "carried_out_by": [
        {
          "id": "https://linked.art/example/person/naumann",
          "type": "Person",
          "_label": "Otto Naumann"
        }
      ],
      "transferred_title_of": [
        {
          "id": "https://linked.art/example/object/spring",
          "type": "HumanMadeObject",
          "_label": "Spring"
        }
      ],
      "transferred_title_from": [
        {
          "id": "https://linked.art/example/group/payne_heirs",
          "type": "Group",
          "_label": "Family of Oliver Payne"
        }
      ],
      "transferred_title_to": [
        {
          "id": "https://linked.art/example/group/getty",
          "type": "Group",
          "_label": "J. Paul Getty Museum"
        }
      ]
    }
  ]
}

=== linked-art/linked.art/docs/example/provenance/coffin_promise/40.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/provenance/coffin_promise/40",
  "type": "Activity",
  "_label": "Promised Gift of Painting",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300055863",
      "type": "Type",
      "_label": "Provenance Activity"
    }
  ],
  "part": [
    {
      "type": "Activity",
      "_label": "Promise of Gift",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435599",
          "type": "Type",
          "_label": "Promise"
        }
      ]
    }
  ]
}

=== linked-art/linked.art/docs/example/provenance/manet_proust/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/provenance/manet_proust/1",
  "type": "Activity",
  "_label": "Purchase of Spring by Proust",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300055863",
      "type": "Type",
      "_label": "Provenance Activity"
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300404670",
          "type": "Type",
          "_label": "Primary Name"
        }
      ],
      "content": "Purchase of Spring by Proust from Manet"
    }
  ],
  "timespan": {
    "type": "TimeSpan",
    "begin_of_the_begin": "1881-01-01T00:00:00Z",
    "end_of_the_end": "1883-12-31T23:59:59Z"
  },
  "part": [
    {
      "type": "Acquisition",
      "_label": "Ownership of Spring to Proust",
      "transferred_title_of": [
        {
          "id": "https://linked.art/example/object/spring",
          "type": "HumanMadeObject",
          "_label": "Spring"
        }
      ],
      "transferred_title_from": [
        {
          "id": "https://linked.art/example/person/manet",
          "type": "Person",
          "_label": "Manet"
        }
      ],
      "transferred_title_to": [
        {
          "id": "https://linked.art/example/person/proust",
          "type": "Person",
          "_label": "Proust"
        }
      ]
    },
    {
      "type": "Payment",
      "_label": "3000 Francs to Manet",
      "paid_amount": {
        "type": "MonetaryAmount",
        "value": 3000,
        "currency": {
          "id": "http://vocab.getty.edu/aat/300412016",
          "type": "Currency",
          "_label": "French Francs"
        }
      },
      "paid_from": [
        {
          "id": "https://linked.art/example/person/proust",
          "type": "Person",
          "_label": "Proust"
        }
      ],
      "paid_to": [
        {
          "id": "https://linked.art/example/person/manet",
          "type": "Person",
          "_label": "Manet"
        }
      ]
    }
  ]
}
