=== linked-art/linked.art/docs/api/1.0/schema/set.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://linked.art/api/1.0/schema/set.json",
	"title": "Collection Schema",
	"description": "_la:Set_\nA collection of other resources, such as a set of objects or places.\n[API](https://linked.art/api/1.0/endpoint/set/) | [Model](https://linked.art/model/collection/)",
	"type": "object",
	"properties": {
		"@context": {"$ref": "core.json#/definitions/ContextStringOrArray"},
		"id": {"$ref": "core.json#/definitions/idProp"},				
		"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
			{"title": "Specific", "type": "string", "const": "Set"}]},
		"_label": {"$ref": "core.json#/definitions/labelProp"},
		"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
		"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
		"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},
		"equivalent": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/equivalentProp"}, 
			{"title": "Specific", "description": "List of equivalent `Set` entities", "type": "array", "items": {"$ref": "core.json#/definitions/SetRef"}}]},
		"representation": {"$ref": "core.json#/definitions/representationProp"},
		"member_of": {"$ref": "core.json#/definitions/member_ofSetProp"},
		"subject_of": {"$ref": "core.json#/definitions/subject_ofProp"},
		"attributed_by": {"$ref": "core.json#/definitions/attributed_byRelProp"},
		"dimension": {"$ref": "core.json#/definitions/dimensionProp"},
		"about": {"$ref": "core.json#/definitions/aboutProp"},

		"members_exemplified_by": {"description": "Great big bucket for arbitrary data here :(", "type":"array"},
		"used_for": {
			"title": "crm:P16i_was_used_for", 
			"description": "", 
			"type": "array", 
			"items": {"$ref": "core.json#/definitions/Activity"}},

		"created_by": {"title": "crm:P94i_was_created_by", "$ref": "core.json#/definitions/Creation"}

	},
	"required": ["@context", "id", "type", "_label"],
	"additionalProperties": false
}

=== linked-art/linked.art/docs/example/set/archive_asc/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/set/archive_asc/1",
  "type": "Set",
  "_label": "Alfred Stiegliz Correspondence",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300404022",
      "type": "Type",
      "_label": "Archival Grouping"
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300404670",
          "type": "Type",
          "_label": "Primary Name"
        }
      ],
      "content": "Alfred Stiegliz Correspondence"
    }
  ]
}

=== linked-art/linked.art/docs/example/set/rijks_paintings/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/set/rijks_paintings/1",
  "type": "Set",
  "_label": "Paintings of the Rijksmuseum",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300025976",
      "type": "Type",
      "_label": "Collection"
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300404670",
          "type": "Type",
          "_label": "Primary Name"
        }
      ],
      "content": "Paintings of the Rijksmuseum"
    }
  ],
  "member_of": [
    {
      "id": "https://linked.art/example/set/rijks_objects",
      "type": "Set",
      "_label": "Collection of the Rijksmuseum"
    }
  ],
  "used_for": [
    {
      "type": "Activity",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300054277",
          "type": "Type",
          "_label": "Curating"
        }
      ],
      "carried_out_by": [
        {
          "id": "https://linked.art/example/group/rijks_paintings_dept",
          "type": "Group",
          "_label": "Paintings Department"
        }
      ]
    }
  ]
}
