=== linked-art/linked.art/docs/api/1.0/schema/set.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://linked.art/api/1.0/schema/set.json",
	"title": "Collection Schema",
	"description": "_la:Set_\nA collection of other resources, such as a set of objects or places.\n[API](https://linked.art/api/1.0/endpoint/set/) | [Model](https://linked.art/model/collection/)",
	"type": "object",
	"properties": {
		"@context": {"$ref": "core.json#/definitions/ContextStringOrArray"},
		"id": {"$ref": "core.json#/definitions/idProp"},				
		"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
			{"title": "Specific", "type": "string", "const": "Set"}]},
		"_label": {"$ref": "core.json#/definitions/labelProp"},
		"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
		"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
		"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},
		"equivalent": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/equivalentProp"}, 
			{"title": "Specific", "description": "List of equivalent `Set` entities", "type": "array", "items": {"$ref": "core.json#/definitions/SetRef"}}]},
		"representation": {"$ref": "core.json#/definitions/representationProp"},
		"member_of": {"$ref": "core.json#/definitions/member_ofSetProp"},
		"subject_of": {"$ref": "core.json#/definitions/subject_ofProp"},
		"attributed_by": {"$ref": "core.json#/definitions/attributed_byRelProp"},
		"dimension": {"$ref": "core.json#/definitions/dimensionProp"},
		"about": {"$ref": "core.json#/definitions/aboutProp"},

		"members_exemplified_by": {"description": "Great big bucket for arbitrary data here :(", "type":"array"},
		"used_for": {
			"title": "crm:P16i_was_used_for", 
			"description": "", 
			"type": "array", 
			"items": {"$ref": "core.json#/definitions/Activity"}},

		"created_by": {"title": "crm:P94i_was_created_by", "$ref": "core.json#/definitions/Creation"}

	},
	"required": ["@context", "id", "type", "_label"],
	"additionalProperties": false
}

=== linked-art/linked.art/docs/example/set/archive_sfl/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/set/archive_sfl/1",
  "type": "Set",
  "_label": "Stieglitz Family Letters",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300404023",
      "type": "Type",
      "_label": "Archival SubGrouping"
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300404670",
          "type": "Type",
          "_label": "Primary Name"
        }
      ],
      "content": "Stieglitz Family Letters"
    }
  ],
  "member_of": [
    {
      "id": "https://linked.art/example/set/archive_asc",
      "type": "Set",
      "_label": "Alfred Stiegliz Correspondence"
    }
  ]
}

=== linked-art/linked.art/docs/example/set/rijks_objects/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/set/rijks_objects/1",
  "type": "Set",
  "_label": "Collection of the Rijksmuseum",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300025976",
      "type": "Type",
      "_label": "Collection"
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300404670",
          "type": "Type",
          "_label": "Primary Name"
        }
      ],
      "content": "Collection of the Rijksmuseum"
    }
  ]
}

=== linked-art/linked.art/docs/example/set/24477_16_objects/2.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/set/24477_16_objects/2",
  "type": "Set",
  "_label": "Set of Objects for Lot 16",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300411307",
      "type": "Type",
      "_label": "Auction Lot"
    }
  ],
  "dimension": [
    {
      "type": "MonetaryAmount",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300417244",
          "type": "Type",
          "_label": "Estimated Price"
        }
      ],
      "value": 25000000,
      "currency": {
        "id": "http://vocab.getty.edu/aat/300411994",
        "type": "Currency",
        "_label": "US Dollars",
        "notation": "USD"
      }
    }
  ]
}

=== linked-art/linked.art/docs/example/set/exhset/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/set/exhset/1",
  "type": "Set",
  "_label": "Exhibition objects",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300378926",
      "type": "Type",
      "_label": "Exhibition Collection"
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300404670",
          "type": "Type",
          "_label": "Primary Name"
        }
      ],
      "content": "Objects in Manet and Modern Beauty"
    }
  ],
  "referred_to_by": [
    {
      "type": "LinguisticObject",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435416",
          "type": "Type",
          "_label": "Description",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300418049",
              "type": "Type",
              "_label": "Brief Text"
            }
          ]
        }
      ],
      "content": "Objects in the exhibition Manet and Modern Beauty at the Art Institute of Chicago and the Getty Museum"
    }
  ],
  "created_by": {
    "type": "Creation",
    "timespan": {
      "type": "TimeSpan",
      "begin_of_the_begin": "2019-05-01T00:00:00Z",
      "end_of_the_end": "2019-05-01T23:59:59Z"
    }
  }
}

=== linked-art/linked.art/docs/example/set/exhset/2.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/set/exhset/2",
  "type": "Set",
  "_label": "Exhibition objects",
  "members_exemplified_by": [
    {
      "type": "HumanMadeObject",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300033618",
          "type": "Type",
          "_label": "Painting",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300435443",
              "type": "Type",
              "_label": "Type of Work"
            }
          ]
        }
      ],
      "produced_by": {
        "type": "Production",
        "carried_out_by": [
          {
            "id": "http://vocab.getty.edu/ulan/500010363",
            "type": "Person",
            "_label": "Manet"
          }
        ]
      }
    }
  ]
}

=== linked-art/linked.art/docs/example/set/24477_16_objects/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/set/24477_16_objects/1",
  "type": "Set",
  "_label": "Set of Objects for Lot 16",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300411307",
      "type": "Type",
      "_label": "Auction Lot"
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300404670",
          "type": "Type",
          "_label": "Primary Name"
        }
      ],
      "content": "Lot 16: Le Printemps"
    },
    {
      "type": "Identifier",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300404628",
          "type": "Type",
          "_label": "Lot Number"
        }
      ],
      "content": "16"
    }
  ]
}

=== linked-art/linked.art/docs/example/set/2.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/set/2",
  "type": "Set",
  "_label": "Set of Objects for Lot 812",
  "dimension": [
    {
      "type": "MonetaryAmount",
      "_label": "$500",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300417242",
          "type": "Type",
          "_label": "Starting Price"
        }
      ],
      "value": 500,
      "identified_by": [
        {
          "type": "Name",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300404669",
              "type": "Type",
              "_label": "Display Title"
            }
          ],
          "content": "500 US Dollars"
        }
      ],
      "referred_to_by": [
        {
          "type": "LinguisticObject",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300027200",
              "type": "Type",
              "_label": "Note",
              "classified_as": [
                {
                  "id": "http://vocab.getty.edu/aat/300418049",
                  "type": "Type",
                  "_label": "Brief Text"
                }
              ]
            }
          ],
          "content": "From personal correspondence"
        }
      ],
      "currency": {
        "id": "http://vocab.getty.edu/aat/300411994",
        "type": "Currency",
        "_label": "US Dollars",
        "notation": "USD"
      }
    }
  ]
}

=== linked-art/linked.art/docs/example/set/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/set/1",
  "type": "Set",
  "_label": "Collection of the Met",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300025976",
      "type": "Type",
      "_label": "Collection"
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "content": "Art Collection of the Metropolitan Museum of Art"
    }
  ],
  "referred_to_by": [
    {
      "type": "LinguisticObject",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435416",
          "type": "Type",
          "_label": "Description",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300418049",
              "type": "Type",
              "_label": "Brief Text"
            }
          ]
        }
      ],
      "content": "Over 2 million works, divided into 17 curatorial departments"
    }
  ],
  "created_by": {
    "type": "Creation",
    "timespan": {
      "type": "TimeSpan",
      "_label": "April 13th, 1870",
      "begin_of_the_begin": "1870-04-13T00:00:00Z",
      "end_of_the_end": "1870-04-13T23:59:59Z"
    }
  }
}
