=== linked-art/linked.art/docs/api/1.0/schema/text.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://linked.art/api/1.0/schema/text.json",
	"title": "Text Schema",
	"description": "_crm:E33\\_Linguistic\\_Object_\nTextual content expressed in one or more human languages, which might or might not be written down on any physical carrier.\nSee: [API](https://linked.art/api/1.0/endpoint/textual_work/) | [Model](https://linked.art/model/document/)",
	"type": "object",
	"properties": {
		"@context": {"$ref": "core.json#/definitions/ContextStringOrArray"},
		"id": {"$ref": "core.json#/definitions/idProp"},				
		"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
			{"title": "Specific", "type": "string", "const": "LinguisticObject"}]},
		"_label": {"$ref": "core.json#/definitions/labelProp"},
		"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
		"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
		"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},
		"equivalent": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/equivalentProp"}, 
			{"title": "Specific", "description": "List of equivalent `LinguisticObject` entities", "type": "array", "items": {"$ref": "core.json#/definitions/LinguisticObjectRef"}}]},
		"representation": {"$ref": "core.json#/definitions/representationProp"},
		"member_of": {"$ref": "core.json#/definitions/member_ofSetProp"},
		"subject_of": {"$ref": "core.json#/definitions/subject_ofProp"},
		"attributed_by": {"$ref": "core.json#/definitions/attributed_byRelProp"},
		"dimension": {"$ref": "core.json#/definitions/dimensionProp"},
		"subject_to": {"$ref": "core.json#/definitions/subject_toProp"},		
        "format": {"$ref": "core.json#/definitions/formatProp"},
		"language": {"$ref": "core.json#/definitions/languageProp"},
		"about": {"$ref": "core.json#/definitions/aboutProp"},
		"created_by": {"title": "crm:P94i_was_created_by", "$ref": "core.json#/definitions/Creation"},
		"used_for": {
			"title": "crm:P16i_was_used_for", 
			"description": "", 
			"type": "array", 
			"items": {"$ref": "core.json#/definitions/Activity"}},
		"part_of": {
			"title": "crm:P106i_forms_part_of",
			"description": "Reference to another Linguistic Object of which this is part", 
			"type": "array",
			"items": {"$ref": "core.json#/definitions/LinguisticObjectRef"}},
        "content": {"$ref": "core.json#/definitions/contentProp"}
	},
	"required": ["@context", "id", "type", "_label"],
	"additionalProperties": false
}

=== linked-art/linked.art/docs/example/text/harpers/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/text/harpers/1",
  "type": "LinguisticObject",
  "_label": "Textual component of Harpers",
  "content": "Harper's. January contains Roden's corner. A Novel by Henry Seton Merriman [...]",
  "part_of": [
    {
      "id": "https://linked.art/example/visual/harpers",
      "type": "VisualItem",
      "_label": "Visual Content of Harpers"
    }
  ]
}

=== linked-art/linked.art/docs/example/text/koot_nightwatch/2.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/text/koot_nightwatch/2",
  "type": "LinguisticObject",
  "_label": "Content of Koot's Night Watch",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300060417",
      "type": "Type",
      "_label": "Monograph",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435443",
          "type": "Type",
          "_label": "Type of Work"
        }
      ]
    }
  ],
  "created_by": {
    "type": "Creation",
    "_label": "Koot's writing of the work",
    "carried_out_by": [
      {
        "id": "https://linked.art/example/person/koot",
        "type": "Person",
        "_label": "Ton Koot"
      }
    ]
  },
  "used_for": [
    {
      "type": "Activity",
      "_label": "MI's Publishing",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300054686",
          "type": "Type",
          "_label": "Publishing"
        }
      ],
      "timespan": {
        "type": "TimeSpan",
        "begin_of_the_begin": "1969-01-01T00:00:00Z",
        "end_of_the_end": "1969-12-31T23:59:59Z"
      },
      "carried_out_by": [
        {
          "id": "https://linked.art/example/group/meulenhoff",
          "type": "Group",
          "_label": "Meulenhoff International"
        }
      ]
    }
  ]
}

=== linked-art/linked.art/docs/example/text/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/text/1",
  "type": "LinguisticObject",
  "_label": "Example Text",
  "subject_to": [
    {
      "type": "Right",
      "_label": "Public Domain status of Example Text",
      "classified_as": [
        {
          "id": "https://creativecommons.org/publicdomain/zero/1.0/",
          "type": "Type",
          "_label": "cc0"
        }
      ],
      "identified_by": [
        {
          "type": "Name",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300404669",
              "type": "Type",
              "_label": "Display Title"
            }
          ],
          "content": "Public Domain"
        }
      ]
    }
  ]
}

=== linked-art/linked.art/docs/example/text/koot_nightwatch_ch1/2.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/text/koot_nightwatch_ch1/2",
  "type": "LinguisticObject",
  "_label": "Chapter 1 of Koot",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300311699",
      "type": "Type",
      "_label": "Chapter",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435443",
          "type": "Type",
          "_label": "Type of Work"
        }
      ]
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300404670",
          "type": "Type",
          "_label": "Primary Name"
        }
      ],
      "content": "Introduction"
    }
  ],
  "referred_to_by": [
    {
      "type": "LinguisticObject",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435440",
          "type": "Type",
          "_label": "Pagination Statement",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300418049",
              "type": "Type",
              "_label": "Brief Text"
            }
          ]
        }
      ],
      "content": "5 - 15"
    }
  ],
  "dimension": [
    {
      "type": "Dimension",
      "_label": "10 pages",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300404433",
          "type": "Type",
          "_label": "Count Of"
        }
      ],
      "value": 10,
      "unit": {
        "id": "http://vocab.getty.edu/aat/300194222",
        "type": "MeasurementUnit",
        "_label": "Pages"
      }
    }
  ]
}

=== linked-art/linked.art/docs/example/text/catalog_24477/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/text/catalog_24477/1",
  "type": "LinguisticObject",
  "_label": "Auction Catalog",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300026068",
      "type": "Type",
      "_label": "Auction Catalog",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435443",
          "type": "Type",
          "_label": "Type of Work"
        }
      ]
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300404670",
          "type": "Type",
          "_label": "Primary Name"
        }
      ],
      "content": "Impressionist & Modern Evening Sale Catalog"
    }
  ],
  "about": [
    {
      "id": "https://linked.art/example/event/christies_24477",
      "type": "Activity",
      "_label": "Impressionist Sale"
    }
  ]
}

=== linked-art/linked.art/docs/example/text/koot_nightwatch_ch1/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/text/koot_nightwatch_ch1/1",
  "type": "LinguisticObject",
  "_label": "Chapter 1 of Koot",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300311699",
      "type": "Type",
      "_label": "Chapter",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435443",
          "type": "Type",
          "_label": "Type of Work"
        }
      ]
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300404670",
          "type": "Type",
          "_label": "Primary Name"
        }
      ],
      "content": "Introduction"
    }
  ],
  "part_of": [
    {
      "id": "https://linked.art/example/text/koot_nightwatch",
      "type": "LinguisticObject",
      "_label": "Koot's Night Watch"
    }
  ]
}

=== linked-art/linked.art/docs/example/text/koot_nightwatch/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/text/koot_nightwatch/1",
  "type": "LinguisticObject",
  "_label": "Content of Koot's Night Watch",
  "identified_by": [
    {
      "type": "Name",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300404670",
          "type": "Type",
          "_label": "Primary Name"
        }
      ],
      "content": "Rembrant's Night Watch. A Fascinating Story"
    }
  ],
  "part_of": [
    {
      "id": "https://linked.art/example/concept/koot_idea",
      "type": "PropositionalObject",
      "_label": "Koot's Conceptualization"
    }
  ]
}

=== linked-art/linked.art/docs/example/text/koot_nightwatch/3.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/text/koot_nightwatch/3",
  "type": "LinguisticObject",
  "_label": "Content of Koot's Night Watch",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300060417",
      "type": "Type",
      "_label": "Monograph",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435443",
          "type": "Type",
          "_label": "Type of Work"
        }
      ]
    }
  ],
  "about": [
    {
      "id": "https://linked.art/example/object/nightwatch",
      "type": "HumanMadeObject",
      "_label": "The Night Watch"
    }
  ]
}
