=== linked-art/linked.art/docs/api/1.0/schema/text.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://linked.art/api/1.0/schema/text.json",
	"title": "Text Schema",
	"description": "_crm:E33\\_Linguistic\\_Object_\nTextual content expressed in one or more human languages, which might or might not be written down on any physical carrier.\nSee: [API](https://linked.art/api/1.0/endpoint/textual_work/) | [Model](https://linked.art/model/document/)",
	"type": "object",
	"properties": {
		"@context": {"$ref": "core.json#/definitions/ContextStringOrArray"},
		"id": {"$ref": "core.json#/definitions/idProp"},				
		"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
			{"title": "Specific", "type": "string", "const": "LinguisticObject"}]},
		"_label": {"$ref": "core.json#/definitions/labelProp"},
		"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
		"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
		"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},
		"equivalent": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/equivalentProp"}, 
			{"title": "Specific", "description": "List of equivalent `LinguisticObject` entities", "type": "array", "items": {"$ref": "core.json#/definitions/LinguisticObjectRef"}}]},
		"representation": {"$ref": "core.json#/definitions/representationProp"},
		"member_of": {"$ref": "core.json#/definitions/member_ofSetProp"},
		"subject_of": {"$ref": "core.json#/definitions/subject_ofProp"},
		"attributed_by": {"$ref": "core.json#/definitions/attributed_byRelProp"},
		"dimension": {"$ref": "core.json#/definitions/dimensionProp"},
		"subject_to": {"$ref": "core.json#/definitions/subject_toProp"},		
        "format": {"$ref": "core.json#/definitions/formatProp"},
		"language": {"$ref": "core.json#/definitions/languageProp"},
		"about": {"$ref": "core.json#/definitions/aboutProp"},
		"created_by": {"title": "crm:P94i_was_created_by", "$ref": "core.json#/definitions/Creation"},
		"used_for": {
			"title": "crm:P16i_was_used_for", 
			"description": "", 
			"type": "array", 
			"items": {"$ref": "core.json#/definitions/Activity"}},
		"part_of": {
			"title": "crm:P106i_forms_part_of",
			"description": "Reference to another Linguistic Object of which this is part", 
			"type": "array",
			"items": {"$ref": "core.json#/definitions/LinguisticObjectRef"}},
        "content": {"$ref": "core.json#/definitions/contentProp"}
	},
	"required": ["@context", "id", "type", "_label"],
	"additionalProperties": false
}

=== linked-art/linked.art/docs/example/text/0.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/text/0",
  "type": "LinguisticObject",
  "_label": "Gainsborough by Hayes",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300060417",
      "type": "Type",
      "_label": "Monograph",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435443",
          "type": "Type",
          "_label": "Type of Work"
        }
      ]
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300404670",
          "type": "Type",
          "_label": "Primary Name"
        }
      ],
      "content": "Gainsborough: Paintings and Drawings"
    },
    {
      "type": "Identifier",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300417443",
          "type": "Type",
          "_label": "ISBN Identifier"
        }
      ],
      "content": "0714816396"
    }
  ],
  "referred_to_by": [
    {
      "type": "LinguisticObject",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300026032",
          "type": "Type",
          "_label": "Abstract",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300418049",
              "type": "Type",
              "_label": "Brief Text"
            }
          ]
        }
      ],
      "content": "A thorough analysis of the artist's life and work"
    }
  ],
  "about": [
    {
      "id": "http://vocab.getty.edu/ulan/500115200",
      "type": "Person",
      "_label": "Gainsborough, Thomas"
    }
  ],
  "language": [
    {
      "id": "http://vocab.getty.edu/aat/300388277",
      "type": "Language",
      "_label": "English",
      "notation": "en"
    }
  ],
  "used_for": [
    {
      "type": "Activity",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300054686",
          "type": "Type",
          "_label": "Publishing"
        }
      ],
      "timespan": {
        "type": "TimeSpan",
        "_label": "1975",
        "begin_of_the_begin": "1975-01-01T00:00:00Z",
        "end_of_the_end": "1975-12-31T23:59:59Z"
      },
      "took_place_at": [
        {
          "type": "Place",
          "_label": "New York"
        }
      ],
      "carried_out_by": [
        {
          "type": "Group",
          "_label": "Phaidon"
        }
      ]
    }
  ],
  "created_by": {
    "type": "Creation",
    "carried_out_by": [
      {
        "type": "Person",
        "_label": "Hayes, John"
      }
    ]
  }
}

=== linked-art/linked.art/docs/example/text/koot_nightwatch/40.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/text/koot_nightwatch/40",
  "type": "LinguisticObject",
  "_label": "Content of Koot's Night Watch",
  "used_for": [
    {
      "type": "Activity",
      "_label": "MI's Publishing",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300054686",
          "type": "Type",
          "_label": "Publishing"
        }
      ],
      "carried_out_by": [
        {
          "id": "https://linked.art/example/group/meulenhoff",
          "type": "Group",
          "_label": "Meulenhoff International"
        }
      ]
    }
  ]
}

=== linked-art/linked.art/docs/example/text/rembrandtjaccuse/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/text/rembrandtjaccuse/1",
  "type": "LinguisticObject",
  "_label": "Rembrandt's J'accuse",
  "created_by": {
    "type": "Creation",
    "timespan": {
      "type": "TimeSpan",
      "_label": "2008",
      "begin_of_the_begin": "2008-01-01T00:00:00Z",
      "end_of_the_end": "2008-12-31T23:59:59Z"
    },
    "part": [
      {
        "type": "Creation",
        "classified_as": [
          {
            "id": "http://vocab.getty.edu/aat/300025654",
            "type": "Type",
            "_label": "Director"
          }
        ],
        "carried_out_by": [
          {
            "id": "https://linked.art/example/person/greenaway",
            "type": "Person",
            "_label": "Peter Greenaway"
          }
        ]
      },
      {
        "type": "Creation",
        "classified_as": [
          {
            "id": "http://vocab.getty.edu/aat/300197742",
            "type": "Type",
            "_label": "Producer"
          }
        ],
        "carried_out_by": [
          {
            "id": "https://linked.art/example/person/wolting",
            "type": "Person",
            "_label": "Femke Wolting"
          }
        ]
      }
    ]
  }
}
