=== linked-art/linked.art/content/api/1.0/schema/event.json
{
	"$schema": "http://json-schema.org/schema#",
	"$id": "file:///Users/rs2668/Development/other/linked-art/json-validator/schema/",
	"title": "Event Schema",
	"description": "_crm:E6\\_Event_ or _crm:E7\\_Activity_\nAn event (no person carried it out) or activity (some actor was responsible) that occured.\nSee: [API](https://linked.art/api/1.0/endpoint/event/) | [Model]()",
	"type": "object",
	"properties": {
		"@context": {"$ref": "core.json#/definitions/ContextStringOrArray"},
		"id": {"$ref": "core.json#/definitions/idProp"},				
		"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
			{"title": "Specific", "type": "string", "enum": ["Event", "Activity"]}]},
		"_label": {"$ref": "core.json#/definitions/labelProp"},
		"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
		"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
		"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},
		"equivalent": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/equivalentProp"}, 
			{"title": "Specific", "description": "List of equivalent `Activity` entities", "type": "array", "items": {"$ref": "core.json#/definitions/ActivityRef"}}]},
		"representation": {"$ref": "core.json#/definitions/representationProp"},
		"member_of": {"$ref": "core.json#/definitions/member_ofSetProp"},
		"subject_of": {"$ref": "core.json#/definitions/subject_ofProp"},
		"attributed_by": {"$ref": "core.json#/definitions/attributed_byRelProp"},

		"took_place_at": {"$ref": "core.json#/definitions/took_place_atProp"},
		"timespan": {"$ref": "core.json#/definitions/timespanProp"},
		"caused_by": {"$ref": "core.json#/definitions/caused_byProp"},
		"carried_out_by": {"$ref": "core.json#/definitions/carried_out_byProp"},
		"used_specific_object": {"$ref": "core.json#/definitions/used_specific_objectProp"},
		"influenced_by": {"$ref": "core.json#/definitions/influenced_byProp"},
		"technique": {"$ref": "core.json#/definitions/techniqueProp"},

		"part_of": {"title": "crm:P9i_forms_part_of", "description": "An identified event or activity which this one is part of", "$ref": "core.json#/definitions/EventRefOrActivityRef"}
	},
	"required": ["@context", "id", "type", "_label"],
	"additionalProperties": false
}

=== linked-art/linked.art/docs/example/event/0.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/event/0",
  "type": "Activity",
  "_label": "Foster Auction of March 1820",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300054751",
      "type": "Type",
      "_label": "Auction Event"
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "content": "Edward Foster Auction of March 1820"
    },
    {
      "type": "Identifier",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300404621",
          "type": "Type",
          "_label": "Owner-Assigned Number"
        }
      ],
      "content": "Br1908"
    }
  ],
  "referred_to_by": [
    {
      "type": "LinguisticObject",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435416",
          "type": "Type",
          "_label": "Description",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300418049",
              "type": "Type",
              "_label": "Brief Text"
            }
          ]
        }
      ],
      "content": "Besides paintings, this sale included a few lots with musical instruments and watches. The owners were a number of dealers who regularly consigned their wares to this auctioneer, despite the fact that the title page names \"A Gentleman\" as the owner."
    }
  ],
  "timespan": {
    "type": "TimeSpan",
    "identified_by": [
      {
        "type": "Name",
        "classified_as": [
          {
            "id": "http://vocab.getty.edu/aat/300404669",
            "type": "Type",
            "_label": "Display Title"
          }
        ],
        "content": "1820 Mar 09"
      }
    ],
    "begin_of_the_begin": "1820-03-09T00:00:00Z",
    "end_of_the_end": "1820-03-09T23:59:59Z"
  },
  "took_place_at": [
    {
      "id": "http://vocab.getty.edu/tgn/7011781",
      "type": "Place",
      "_label": "London"
    }
  ],
  "carried_out_by": [
    {
      "id": "http://vocab.getty.edu/ulan/500451765",
      "type": "Group",
      "_label": "Edward Foster & Son"
    }
  ],
  "used_specific_object": [
    {
      "id": "http://example.org/sets/Br1908",
      "type": "Set",
      "_label": "All Auction Lots of Br1908"
    }
  ],
  "equivalent": [
    {
      "id": "http://example.auction/past/foster/1820/03/1",
      "type": "Activity"
    }
  ],
  "subject_of": [
    {
      "id": "http://example.org/catalog/Br1908",
      "type": "LinguisticObject",
      "_label": "Sales Catalog of Br-1908"
    }
  ]
}

=== linked-art/linked.art/docs/example/activity/exha/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/activity/exha/1",
  "type": "Activity",
  "_label": "Manet and Modern Beauty (Getty)",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300054766",
      "type": "Type",
      "_label": "Exhibiting"
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300404670",
          "type": "Type",
          "_label": "Primary Name"
        }
      ],
      "content": "Manet and Modern Beauty"
    }
  ],
  "referred_to_by": [
    {
      "type": "LinguisticObject",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435416",
          "type": "Type",
          "_label": "Description",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300418049",
              "type": "Type",
              "_label": "Brief Text"
            }
          ]
        }
      ],
      "content": "The great painter of modern Paris Edouard Manet famously shocked contemporary audiences with his provocative pictures. The first exhibition ever to explore the last years of his short life, Manet and Modern Beauty highlights a less familiar and more intimate side of this celebrated artist's work."
    }
  ],
  "timespan": {
    "type": "TimeSpan",
    "begin_of_the_begin": "2019-10-08T00:00:00Z",
    "end_of_the_end": "2020-01-12T23:59:59Z"
  },
  "took_place_at": [
    {
      "id": "http://vocab.getty.edu/tgn/7023900",
      "type": "Place",
      "_label": "Los Angeles",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300008389",
          "type": "Type",
          "_label": "City"
        }
      ]
    }
  ],
  "carried_out_by": [
    {
      "id": "http://vocab.getty.edu/ulan/500115988",
      "type": "Group",
      "_label": "Getty Museum",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300312281",
          "type": "Type",
          "_label": "Museum"
        }
      ]
    }
  ],
  "used_specific_object": [
    {
      "id": "https://linked.art/example/set/exhset",
      "type": "Set",
      "_label": "Exhibition objects"
    }
  ],
  "influenced_by": [
    {
      "id": "https://linked.art/example/concept/exhidea",
      "type": "PropositionalObject",
      "_label": "Idea for Manet and Modern Beauty"
    }
  ]
}

=== linked-art/linked.art/docs/example/event/exhab/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/event/exhab/1",
  "type": "Activity",
  "_label": "Manet and Modern Beauty",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300054773",
      "type": "Type",
      "_label": "Exhibiting in multiple locations"
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300404670",
          "type": "Type",
          "_label": "Primary Name"
        }
      ],
      "content": "Manet and Modern Beauty"
    }
  ],
  "timespan": {
    "type": "TimeSpan",
    "begin_of_the_begin": "2019-05-26T00:00:00Z",
    "end_of_the_end": "2020-01-12T23:59:59Z"
  },
  "influenced_by": [
    {
      "id": "https://linked.art/example/concept/exhidea",
      "type": "PropositionalObject",
      "_label": "Idea for Manet and Modern Beauty"
    }
  ]
}

=== linked-art/linked.art/docs/example/event/christies_24477_16/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/event/christies_24477_16/1",
  "type": "Activity",
  "_label": "Auction of Lot 16",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300420001",
      "type": "Type",
      "_label": "Auction of Lot"
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300404670",
          "type": "Type",
          "_label": "Primary Name"
        }
      ],
      "content": "Auction of Lot 16"
    }
  ],
  "used_specific_object": [
    {
      "id": "https://linked.art/example/set/24477_16_objects",
      "type": "Set",
      "_label": "Lot 16"
    }
  ],
  "part_of": [
    {
      "id": "https://linked.art/example/event/christies_24477",
      "type": "Activity"
    }
  ]
}

=== linked-art/linked.art/docs/example/event/stowe/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/event/stowe/1",
  "type": "Activity",
  "_label": "Auction of Stowe House",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300054751",
      "type": "Type",
      "_label": "Auction Event"
    }
  ],
  "timespan": {
    "type": "TimeSpan",
    "identified_by": [
      {
        "type": "Name",
        "content": "40 days in August and September, 1848"
      }
    ],
    "begin_of_the_begin": "1848-08-01T00:00:00Z",
    "end_of_the_begin": "1848-08-20T23:59:59Z",
    "begin_of_the_end": "1848-09-09T00:00:00Z",
    "end_of_the_end": "1848-09-30T23:59:59Z",
    "duration": {
      "type": "Dimension",
      "value": 3,
      "unit": {
        "id": "http://vocab.getty.edu/aat/300379242",
        "type": "MeasurementUnit",
        "_label": "days"
      }
    }
  }
}

=== linked-art/linked.art/docs/example/event/christies_24477/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/event/christies_24477/1",
  "type": "Activity",
  "_label": "Impressionist Sale",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300054751",
      "type": "Type",
      "_label": "Auction Event"
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300404670",
          "type": "Type",
          "_label": "Primary Name"
        }
      ],
      "content": "Impressionist & Modern Evening Sale"
    }
  ],
  "timespan": {
    "type": "TimeSpan",
    "_label": "Nov 5, 2014",
    "begin_of_the_begin": "2014-11-05T17:00:00Z",
    "end_of_the_end": "2014-11-05T23:59:59Z"
  },
  "took_place_at": [
    {
      "id": "https://linked.art/example/place/christies_nyc",
      "type": "Place",
      "_label": "Christie's, New York",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300005234",
          "type": "Type",
          "_label": "Auction House (place)"
        }
      ]
    }
  ],
  "carried_out_by": [
    {
      "id": "https://linked.art/example/group/christies",
      "type": "Group",
      "_label": "Christie's",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300417515",
          "type": "Type",
          "_label": "Auction House (organization)"
        }
      ]
    }
  ]
}

=== linked-art/linked.art/docs/example/event/operation_nightwatch/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/event/operation_nightwatch/1",
  "type": "Activity",
  "_label": "Conservation Project",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300404519",
      "type": "Type",
      "_label": "Conservation Activity"
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300404670",
          "type": "Type",
          "_label": "Primary Name"
        }
      ],
      "content": "Operation Night Watch"
    }
  ],
  "referred_to_by": [
    {
      "type": "LinguisticObject",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435416",
          "type": "Type",
          "_label": "Description",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300418049",
              "type": "Type",
              "_label": "Brief Text"
            }
          ]
        }
      ],
      "content": "Operation Night Watch is the biggest and most wide-ranging ever study of Rembrandtâ€™s most famous painting."
    }
  ],
  "timespan": {
    "type": "TimeSpan",
    "begin_of_the_begin": "2019-01-01T00:00:00Z",
    "end_of_the_end": "2023-12-31T23:59:59Z"
  },
  "carried_out_by": [
    {
      "id": "https://linked.art/example/group/rijksmuseum",
      "type": "Group",
      "_label": "Rijksmuseum"
    },
    {
      "id": "https://linked.art/example/group/akzonobel",
      "type": "Group",
      "_label": "AkzoNobel"
    }
  ]
}

=== linked-art/linked.art/docs/example/activity/exha/40.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/activity/exha/40",
  "type": "Activity",
  "_label": "Manet and Modern Beauty (Getty)",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300054766",
      "type": "Type",
      "_label": "Exhibiting"
    }
  ]
}
