=== linked-art/linked.art/content/api/1.0/schema/event.json
{
	"$schema": "http://json-schema.org/schema#",
	"$id": "file:///Users/rs2668/Development/other/linked-art/json-validator/schema/",
	"title": "Event Schema",
	"description": "_crm:E6\\_Event_ or _crm:E7\\_Activity_\nAn event (no person carried it out) or activity (some actor was responsible) that occured.\nSee: [API](https://linked.art/api/1.0/endpoint/event/) | [Model]()",
	"type": "object",
	"properties": {
		"@context": {"$ref": "core.json#/definitions/ContextStringOrArray"},
		"id": {"$ref": "core.json#/definitions/idProp"},				
		"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
			{"title": "Specific", "type": "string", "enum": ["Event", "Activity"]}]},
		"_label": {"$ref": "core.json#/definitions/labelProp"},
		"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
		"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
		"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},
		"equivalent": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/equivalentProp"}, 
			{"title": "Specific", "description": "List of equivalent `Activity` entities", "type": "array", "items": {"$ref": "core.json#/definitions/ActivityRef"}}]},
		"representation": {"$ref": "core.json#/definitions/representationProp"},
		"member_of": {"$ref": "core.json#/definitions/member_ofSetProp"},
		"subject_of": {"$ref": "core.json#/definitions/subject_ofProp"},
		"attributed_by": {"$ref": "core.json#/definitions/attributed_byRelProp"},

		"took_place_at": {"$ref": "core.json#/definitions/took_place_atProp"},
		"timespan": {"$ref": "core.json#/definitions/timespanProp"},
		"caused_by": {"$ref": "core.json#/definitions/caused_byProp"},
		"carried_out_by": {"$ref": "core.json#/definitions/carried_out_byProp"},
		"used_specific_object": {"$ref": "core.json#/definitions/used_specific_objectProp"},
		"influenced_by": {"$ref": "core.json#/definitions/influenced_byProp"},
		"technique": {"$ref": "core.json#/definitions/techniqueProp"},

		"part_of": {"title": "crm:P9i_forms_part_of", "description": "An identified event or activity which this one is part of", "$ref": "core.json#/definitions/EventRefOrActivityRef"}
	},
	"required": ["@context", "id", "type", "_label"],
	"additionalProperties": false
}

=== linked-art/linked.art/docs/example/activity/exhb/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/activity/exhb/1",
  "type": "Activity",
  "_label": "Manet and Modern Beauty (AIC)",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300054766",
      "type": "Type",
      "_label": "Exhibiting"
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300404670",
          "type": "Type",
          "_label": "Primary Name"
        }
      ],
      "content": "Manet and Modern Beauty"
    }
  ],
  "timespan": {
    "type": "TimeSpan",
    "begin_of_the_begin": "2019-05-26T00:00:00Z",
    "end_of_the_end": "2019-09-08T23:59:59Z"
  },
  "took_place_at": [
    {
      "id": "http://vocab.getty.edu/tgn/7013596",
      "type": "Place",
      "_label": "Chicago",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300008389",
          "type": "Type",
          "_label": "City"
        }
      ]
    }
  ],
  "carried_out_by": [
    {
      "id": "http://vocab.getty.edu/ulan/500304669",
      "type": "Group",
      "_label": "Art Institute",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300312281",
          "type": "Type",
          "_label": "Museum"
        }
      ]
    }
  ],
  "used_specific_object": [
    {
      "id": "https://linked.art/example/set/exhset",
      "type": "Set",
      "_label": "Exhibition objects"
    }
  ],
  "part_of": [
    {
      "id": "https://linked.art/example/event/exhab",
      "type": "Activity",
      "_label": "Manet and Modern Beauty"
    }
  ],
  "influenced_by": [
    {
      "id": "https://linked.art/example/concept/exhidea",
      "type": "PropositionalObject",
      "_label": "Idea for Manet and Modern Beauty"
    }
  ]
}

=== linked-art/linked.art/docs/example/event/vesuvius/1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/event/vesuvius/1",
  "type": "Event",
  "_label": "Eruption of Vesuvius",
  "identified_by": [
    {
      "type": "Name",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300404670",
          "type": "Type",
          "_label": "Primary Name"
        }
      ],
      "content": "Eruption of Vesuvius"
    }
  ],
  "timespan": {
    "type": "TimeSpan",
    "begin_of_the_begin": "0079-08-24T12:00:00Z",
    "end_of_the_end": "0079-08-26T23:59:59Z"
  },
  "took_place_at": [
    {
      "id": "https://linked.art/example/place/vesuvius",
      "type": "Place",
      "_label": "Mount Vesuvius"
    }
  ]
}

=== linked-art/linked.art/docs/example/provenance/manet_proust/40.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/provenance/manet_proust/40",
  "type": "Activity",
  "_label": "Purchase of Spring by Proust",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300055863",
      "type": "Type",
      "_label": "Provenance Activity"
    }
  ]
}

=== linked-art/linked.art/docs/example/provenance/0.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/provenance/0",
  "type": "Activity",
  "_label": "Provenance Activity",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300055863",
      "type": "Type",
      "_label": "Provenance Activity"
    }
  ]
}
