=== linked-art/linked.art/content/api/1.0/schema/image.json
{
	"$schema": "http://json-schema.org/schema#",
	"$id": "file:///Users/rs2668/Development/other/linked-art/json-validator/schema/",
	"title": "Visual Content Schema",
	"description": "_crm:E36\\_Visual\\_Item_\nThe visual content of a work.\nSee: [API](https://linked.art/api/1.0/endpoint/visual_work/) | [Model](https://linked.art/model/object/aboutness/#physical-object-and-visual-work)",
	"type": "object",
	"properties": {
		"@context": {"$ref": "core.json#/definitions/ContextStringOrArray"},
		"id": {"$ref": "core.json#/definitions/idProp"},				
		"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
			{"title": "Specific", "type": "string", "const": "VisualItem"}]},
		"_label": {"$ref": "core.json#/definitions/labelProp"},
		"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
		"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
		"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},
		"equivalent": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/equivalentProp"}, 
			{"title": "Specific", "description": "List of equivalent `VisualItem` entities", "type": "array", "items": {"$ref": "core.json#/definitions/VisualItemRef"}}]},
		"member_of": {"$ref": "core.json#/definitions/member_ofSetProp"},
		"subject_of": {"$ref": "core.json#/definitions/subject_ofProp"},
		"attributed_by": {"$ref": "core.json#/definitions/attributed_byRelProp"},
		"dimension": {"$ref": "core.json#/definitions/dimensionProp"},

		"part_of": {"title": "crm:P106i_forms_part_of", "description": "Another Visual Item which this Visual Item is part of", "$ref": "core.json#/definitions/VisualItemRef"},
		"digitally_shown_by": {"title": "la:digitally_carried_by", "description": "", "type": "array", "items": {"$ref": "core.json#/definitions/DigitalObjectRef"}},
		"shown_by": {"title": "crm:P128i_is_carried_by", "description": "", "type": "array", "items": {"$ref": "core.json#/definitions/HumanMadeObjectRef"}},
		"about": {"title": "crm:P129_is_about", "description": "The main topic(s) of the content", "type": "array", "items": {"$ref": "core.json#/definitions/AnyRef"}},
		"created_by": {"title": "crm:P94i_was_created_by", "$ref": "#/definitions/Creation"},
		"represents": {"title": "crm:P138_represents", "description": "An entity which is represented in this image content", "type": "array", "items": {"$ref": "core.json#/definitions/AnyRef"}},
		"represents_instance_of_type": {"title": "la:represents_instance_of_type", "description": "A Type of an entity, which is represented in this image content", "type": "array", "items": {"$ref": "core.json#/definitions/Concept"}},
		"used_for": {"title": "crm:P16i_was_used_for", "description": "", "type": "array", "items": {"$ref": "core.json#/definitions/Activity"}}

	},
	"definitions": {
		"Creation": {
			"title": "crm:E65_Creation",
			"description": "The creation / writing of the text",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
					{"title": "Specific", "type": "string", "const": "Creation"}]},
				"_label": {"$ref": "core.json#/definitions/labelProp"},
				"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
				"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},
				"took_place_at": {"$ref": "core.json#/definitions/took_place_atProp"},
				"timespan": {"$ref": "core.json#/definitions/timespanProp"},
				"caused_by": {"$ref": "core.json#/definitions/caused_byProp"},
				"carried_out_by": {"$ref": "core.json#/definitions/carried_out_byProp"},
				"used_specific_object": {"$ref": "core.json#/definitions/used_specific_objectProp"},
				"influenced_by": {"$ref": "core.json#/definitions/influenced_byProp"},
				"technique": {"$ref": "core.json#/definitions/techniqueProp"},
				"part_of": {"title": "crm:P9i_forms_part_of", "description": "An identified event or activity which this creation is part of", "$ref": "core.json#/definitions/EventRefOrActivityRef"}
			}
		}
	},
	"required": ["@context", "id", "type", "_label"],
	"additionalProperties": false
}

=== linked-art/linked.art/docs/example/visual/0.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/visual/0",
  "type": "VisualItem",
  "_label": "Appearance of Miro's The Farm",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300021495",
      "type": "Type",
      "_label": "Cubist",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300015646",
          "type": "Type",
          "_label": "Style"
        }
      ]
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "content": "Appearance of The Farm"
    }
  ],
  "referred_to_by": [
    {
      "type": "LinguisticObject",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435416",
          "type": "Type",
          "_label": "Description",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300418049",
              "type": "Type",
              "_label": "Brief Text"
            }
          ]
        }
      ],
      "content": "A brilliant amalgamation of an intense, even primitive, realism with the formal vocabulary of cubism."
    }
  ],
  "represents": [
    {
      "id": "http://vocab.getty.edu/tgn/7300934",
      "type": "Place",
      "_label": "Mont-roig del Camp"
    }
  ],
  "represents_instance_of_type": [
    {
      "id": "http://vocab.getty.edu/aat/300132410",
      "type": "Type",
      "_label": "Tree"
    }
  ],
  "shown_by": [
    {
      "id": "https://www.nga.gov/collection/art-object-69660",
      "type": "HumanMadeObject",
      "_label": "The Farm"
    }
  ],
  "created_by": {
    "type": "Creation",
    "timespan": {
      "type": "TimeSpan",
      "_label": "1921-1922",
      "begin_of_the_begin": "1921-01-01T00:00:00Z",
      "end_of_the_end": "1922-12-31T23:59:59Z"
    },
    "carried_out_by": [
      {
        "id": "http://vocab.getty.edu/ulan/500014094",
        "type": "Person",
        "_label": "Miro"
      }
    ]
  }
}
